<?php

require_once dirname(__FILE__) . '/../../../libs/Qwin.php';
require_once dirname(__FILE__) . '/../../../libs/Qwin/Request.php';

/**
 * Test class for Qwin_Request.
 * Generated by PHPUnit on 2012-01-18 at 09:10:26.
 */
class Qwin_RequestTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Qwin_Request
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Qwin_Request;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Qwin_Request::call
     */
    public function testCall()
    {
        $name = $this->object->call('name');
        $source = isset($_REQUEST['name']) ? $_REQUEST['name'] : null;

        $this->assertEquals($name->source, $source);

        $default = 'default';
        $name2 = $this->object->call('name', $default);
        $source = isset($_REQUEST['name']) ? $_REQUEST['name'] : $default;

        $this->assertEquals($name2->source, $default);
    }
}