<?php
require_once dirname(__FILE__) . '/../../../libs/Qwin.php';
require_once dirname(__FILE__) . '/../../../libs/Qwin/InArray.php';

/**
 * Test class for Qwin_InArray.
 * Generated by PHPUnit on 2012-01-18 at 09:09:02.
 */
class Qwin_InArrayTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Qwin_InArray
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Qwin_InArray;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Qwin_InArray::__invoke
     */
    public function test__invoke() {
        $widget = $this->object;

        $result = $widget->inArray('apple', array('pear', 'apple', 'banana'));

        $this->assertEquals('apple', $result, 'apple found in array');

        $result = $widget->inArray('apple', array('pear', 'banana'));

        $this->assertEquals('pear', $result, 'apple ont found, so pear instead');
    }
}
