<?php

require_once dirname(__FILE__) . '/../../../libs/Qwin.php';
require_once dirname(__FILE__) . '/../../../libs/Qwin/IsQQ.php';

/**
 * Test class for Qwin_IsQQ.
 * Generated by PHPUnit on 2012-01-18 at 09:09:47.
 */
class Qwin_IsQQTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Qwin_IsQQ
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Qwin_IsQQ;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Qwin_IsQQ::call
     */
    public function testCall() {
        $widget = $this->object;

        $widget->source = '1000';

        $this->assertFalse($widget->isQQ(), 'Too short');

        $widget->source = '011111';

        $this->assertFalse($widget->isQQ(), 'Should not start with zero');

        $widget->source = 011111;

        $this->assertFalse($widget->isQQ(), 'Should not start with zero, even digits');

        $widget->source = 134.433;

        $this->assertFalse($widget->isQQ(), 'Not digits');

        $widget->source = 1234567;

        $this->assertTrue($widget->isQQ());
    }

}

?>
