<?php
require_once dirname(__FILE__) . '/../../../libs/Qwin.php';
require_once dirname(__FILE__) . '/../../../libs/Qwin/ToArray.php';

/**
 * Test class for Qwin_ToArray.
 * Generated by PHPUnit on 2012-01-18 at 09:08:58.
 */
class Qwin_ToArrayTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Qwin_ToArray
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Qwin_ToArray;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Qwin_ToArray::call
     */
    public function testCall() {
        $object = $this->object;

        $object->souce = 'this is a string';

        $this->assertInternalType('array', $object->call(), 'String to array');

        $object->souce = 10.6;

        $this->assertInternalType('array', $object->call(), 'Float to array');

        $object->source = true;

        $this->assertInternalType('array', $object->call(), 'Bool to array');

        $object->source = null;

        $this->assertInternalType('array', $object->call(), 'Null to array');

        $object->source = 100;

        $this->assertInternalType('array', $object->call(), 'Int to array');

        $object->source = new stdClass();

        $this->assertInternalType('array', $object->call(), 'Object to array');
    }
}
