<?php
require_once dirname(__FILE__) . '/../../../libs/Qwin.php';
require_once dirname(__FILE__) . '/../../../libs/Qwin/ToText.php';

/**
 * Test class for Qwin_ToText.
 * Generated by PHPUnit on 2012-01-26 at 08:53:30.
 */
class Qwin_ToTextTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Qwin_ToText
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Qwin_ToText;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Qwin_ToText::call
     */
    public function testCall() {
        $widget = $this->object;

        $result = '<a href="attack url">click me!</a>';

        $this->assertEquals('&lt;a&nbsp;href=&quot;attack&nbsp;url&quot;&gt;click&nbsp;me!&lt;/a&gt;', $widget->toText($result));

        $result = '%3Chello%3E';

        $this->assertEquals('&lt;hello&gt;', $widget->toText($result));

        $result = "he's happy.";

        $this->assertEquals('he&#39;s&nbsp;happy.', $widget->toText($result));
    }
}
