<?php
require_once dirname(__FILE__) . '/../../../libs/Qwin.php';
require_once dirname(__FILE__) . '/../../../libs/Qwin/ToHtml.php';

/**
 * Test class for Qwin_ToHtml.
 * Generated by PHPUnit on 2012-01-18 at 09:10:24.
 */
class Qwin_ToHtmlTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Qwin_ToHtml
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Qwin_ToHtml;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Qwin_ToHtml::__invoke
     */
    public function test__invoke() {
        $widget = $this->object;

        $this->assertEquals('&nbsp;&nbsp;&nbsp;&nbsp;string', $widget->toHtml("\tstring"));

        $this->assertFalse(strpos("\t", $widget->toHtml("\tstring")));

        $source = "this\ris\na\r\nstring\n\r";

        $this->assertFalse(strpos("\r", $widget->toHtml($source)));

        $this->assertFalse(strpos("\n", $widget->toHtml($source)));
    }
}
