<?php

require_once dirname(__FILE__) . '/../../../libs/Qwin.php';
require_once dirname(__FILE__) . '/../../../libs/Qwin/ToSource.php';

/**
 * Test class for Qwin_ToSource.
 * Generated by PHPUnit on 2012-01-18 at 09:11:10.
 */
class Qwin_ToSourceTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Qwin_ToSource
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Qwin_ToSource;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Qwin_ToSource::call
     */
    public function testCall() {
        $source = Qwin::getInstance()->variable('soure string');
        
        $this->assertSame($source->source, $source->toSource());
    }

}

?>
