<?php
require_once dirname(__FILE__) . '/../../../libs/Qwin.php';
require_once dirname(__FILE__) . '/../../../libs/Qwin/ToInt.php';

/**
 * Test class for Qwin_ToInt.
 * Generated by PHPUnit on 2012-01-18 at 09:08:51.
 */
class Qwin_ToIntTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Qwin_ToInt
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Qwin_ToInt;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Qwin_ToInt::call
     */
    public function testCall() {
        $object = $this->object;

        $object->souce = 'this is a string';

        $this->assertInternalType('int', $object->call(), 'String to int');

        $object->souce = 10.6;

        $this->assertInternalType('int', $object->call(), 'Float to int');

        $object->source = true;

        $this->assertInternalType('int', $object->call(), 'Bool to int');

        $object->source = null;

        $this->assertInternalType('int', $object->call(), 'Null to int');

        $object->source = array(
            'key' => 'value',
            'key2' => 'value2'
        );

        $this->assertInternalType('int', $object->call(), 'Array to int');

        //$object->source = new stdClass();

        //$this->assertInternalType('int', $object->call(), 'Object to int');
    }

}

?>
