<?php
require_once dirname(__FILE__) . '/../../../libs/Qwin/Storable.php';
require_once dirname(__FILE__) . '/../../../libs/Qwin/Apc.php';

/**
 * Test class for Qwin_Apc.
 * Generated by PHPUnit on 2012-06-07 at 12:03:25.
 */
class Qwin_ApcTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Qwin_Apc
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = Qwin::getInstance()->apc;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Qwin_Apc::get
     * @covers Qwin_Apc::__construct
     */
    public function testGet() {
        $widget = $this->object;

        $widget->remove('test');

        $widget->set('test', __METHOD__);

        $this->assertEquals(__METHOD__, $widget->get('test'), 'get known cache');

        $widget->remove('test');

        $this->assertFalse($widget->get('test'), 'cache has been removed');

        $widget->set('test', __METHOD__, array('expire' => -1));

        $this->assertFalse($widget->get('test'), 'cache is expired');
    }

    /**
     * @covers Qwin_Apc::set
     */
    public function testSet() {
        $widget = $this->object;

        $widget->remove('test2');

        $widget->set('test2', __METHOD__);

        $this->assertEquals(__METHOD__, $widget->get('test2'));
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testDelete().
     */
    public function testDelete() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testAdd().
     */
    public function testAdd() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testReplace().
     */
    public function testReplace() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testIncrement().
     */
    public function testIncrement() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testDecrement().
     */
    public function testDecrement() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}

?>
