<?php
require_once dirname(__FILE__) . '/../../../libs/Qwin.php';

/**
 * Test class for Qwin_ReplaceFirst.
 * Generated by PHPUnit on 2012-02-19 at 09:49:26.
 */
class Qwin_ReplaceFirstTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Qwin_ReplaceFirst
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        Qwin::getInstance();
        $this->object = new Qwin_ReplaceFirst;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Qwin_ReplaceFirst::call
     */
    public function testCall() {
        $widget = $this->object;

        $string = 'abcdefgabcdefg';

        $result = $widget->replaceFirst($string, 'a', 'A');

        $this->assertEquals('Abcdefgabcdefg', $result);

        $result = $widget->replaceFirst($string, 'h', 'A');

        $this->assertEquals('abcdefgabcdefg', $result, 'not found');
    }
}