<?php

require_once dirname(__FILE__) . '/../../../libs/Qwin.php';
require_once dirname(__FILE__) . '/../../../libs/Qwin/Ip.php';

/**
 * Test class for Qwin_Ip.
 * Generated by PHPUnit on 2012-01-18 at 09:10:34.
 */
class Qwin_IpTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Qwin_Ip
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Qwin_Ip;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Qwin_Ip::__invoke
     */
    public function test__invoke() {
        $widget = $this->object;

        // test for HTTP_X_FORWARDED_FOR
        $_SERVER['HTTP_X_FORWARDED_FOR'] = '127.0.0.1';

        $this->assertEquals($_SERVER['HTTP_X_FORWARDED_FOR'], $widget->ip());

        // test for HTTP_CLIENT_IP
        unset($_SERVER['HTTP_X_FORWARDED_FOR']);

        $_SERVER['HTTP_CLIENT_IP'] = '127.0.0.2';

        $this->assertEquals($_SERVER['HTTP_CLIENT_IP'], $widget->ip());

        // test for REMOTE_ADDR
        unset($_SERVER['HTTP_CLIENT_IP']);

        $_SERVER['REMOTE_ADDR'] = '127.0.0.3';

        $this->assertEquals($_SERVER['REMOTE_ADDR'], $widget->ip());

        // test for default value
        unset($_SERVER['REMOTE_ADDR']);

        $this->assertEquals('0.0.0.0', $widget->ip());
    }

}