<?php

require_once dirname(__FILE__) . '/../../../libs/Qwin.php';
require_once dirname(__FILE__) . '/../../../libs/Qwin/IsDigit.php';

/**
 * Test class for Qwin_IsDigit.
 * Generated by PHPUnit on 2012-01-18 at 09:08:37.
 */
class Qwin_IsDigitTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Qwin_IsDigit
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Qwin_IsDigit;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Qwin_IsDigit::__invoke
     */
    public function test__invoke() {
        $widget = $this->object;

        $this->assertTrue($widget->isDigit('123456'));

        $this->assertTrue($widget->isDigit('0123456'));

        $this->assertFalse($widget->isDigit('0.123'));

        $this->assertFalse($widget->isDigit('1 23456'));

        $this->assertFalse($widget->isDigit('string'));
    }

}

?>
