<?php
require_once dirname(__FILE__) . '/../../../libs/Qwin.php';

/**
 * Test class for Qwin_After.
 * Generated by PHPUnit on 2012-02-16 at 06:47:25.
 */
class Qwin_AfterTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Qwin_After
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        Qwin::getInstance();
        $this->object = new Qwin_After;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Qwin_After::call
     */
    public function testCall() {
        $widget = $this->object;

        $widget->source('I like pear and apple.');

        $widget->after('pear', ', orange');

        $this->assertEquals('I like pear, orange and apple.', $widget->source());

        $widget->after('not found', 'anything');

        $this->assertEquals('I like pear, orange and apple.', $widget->source());

        $widget->after('i', ' ', false);

        $this->assertEquals('I  like pear, orange and apple.', $widget->source());
    }

}