<?php
require_once dirname(__FILE__) . '/../../../libs/Qwin/IsMobile.php';

/**
 * Test class for Qwin_IsMobile.
 * Generated by PHPUnit on 2012-06-03 at 12:42:23.
 */
class Qwin_IsMobileTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Qwin_IsMobile
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Qwin_IsMobile;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Qwin_IsMobile
     */
    public function test__invoke()
    {
        $this->assertTrue($this->object->__invoke('13800138000'));

        $this->assertFalse($this->object->__invoke('12000000000'));

        $this->assertFalse($this->object->__invoke('88888888'));
    }
}