<?php

require_once dirname(__FILE__) . '/../../../libs/Qwin.php';
require_once dirname(__FILE__) . '/../../../libs/Qwin/IsFile.php';

/**
 * Test class for Qwin_IsFile.
 * Generated by PHPUnit on 2012-01-18 at 09:09:00.
 */
class Qwin_IsFileTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Qwin_IsFile
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Qwin_IsFile;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Qwin_IsFile::call
     */
    public function testCall() {
        $object = $this->object;
        
        $this->assertEquals(false, $object->isFile(), 'Not File path');
        
        $object->source = __FILE__;
        
        $this->assertTrue($object->isFile(), 'File found');
        
        $path = array_pop(explode(PATH_SEPARATOR, ini_get('include_path')));
        $files = scandir($path);
        foreach ($files as $file) {
            if ('.' == $file || '..' == $file) {
                continue;
            }
            if (is_file($path . DIRECTORY_SEPARATOR . $file)) {
                $object->source = $file;
                $this->assertTrue($object->isFile(), 'File in include path found');
                break;
            }
        }
        
        $object->source = '.file not found';
        
        $this->assertFalse($object->isFile(), 'File not found');
    }

}

?>
