<?php
require_once dirname(__FILE__) . '/../../../libs/Qwin.php';
require_once dirname(__FILE__) . '/../../../libs/Qwin/Each.php';

/**
 * Test class for Qwin_Each.
 * Generated by PHPUnit on 2012-01-18 at 09:09:43.
 */
class Qwin_EachTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Qwin_Each
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Qwin_Each;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    protected $_fruit;

    /**
     * @covers Qwin_Each::__invoke
     */
    public function test__invoke() {
        $widget = $this->object;

        $array = array(
            'apple', 'lemon', 'orange', 'banana', 'pear',
        );

        $widget->each($array, array($this, 'each'));

        $this->assertEquals('orange', $this->_fruit);
    }

    public function each($key, $value)
    {
        if ('orange' == $value) {
            $this->_fruit = $value;
            return false;
        }
    }
}
