<?php
require_once dirname(__FILE__) . '/../../../libs/Qwin.php';

/**
 * Test class for Qwin_Url.
 * Generated by PHPUnit on 2012-01-18 at 09:11:18.
 */
class Qwin_UrlTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Qwin_Url
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        Qwin::getInstance();
        $this->object = new Qwin_Url;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Qwin_Url::__invoke
     */
    public function test__invoke() {
        $widget = $this->object;

        $widget->router->options['baseUri'] = '';

        $widget->router->remove('default');

        $url = $widget->url('user', 'login');

        $this->assertEquals('?module=user&amp;action=login', $url);
    }
}
