<?php

require_once dirname(__FILE__) . '/../../../libs/Qwin.php';
require_once dirname(__FILE__) . '/../../../libs/Qwin/Array.php';

/**
 * Test class for Qwin_Array.
 * Generated by PHPUnit on 2012-01-18 at 09:10:28.
 */
class Qwin_ArrayTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Qwin_Array
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Qwin_Array;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Qwin_Array::call
     */
    public function testCall()
    {
        $widget = $this->object;

        $widget->souce = 'this is a string';

        $this->assertInternalType('array', $widget->array()->source, 'String to array');

        $widget->souce = 10.6;

        $this->assertInternalType('array', $widget->array()->source, 'Float to array');

        $widget->source = true;

        $this->assertInternalType('array', $widget->array()->source, 'Bool to array');

        $widget->source = null;

        $this->assertInternalType('array', $widget->array()->source, 'Null to array');

        $widget->source = 100;

        $this->assertInternalType('array', $widget->array()->source, 'Int to array');

        $widget->source = new stdClass();

        $this->assertInternalType('array', $widget->array()->source, 'Object to array');

        $this->assertInternalType('array', $widget->array('string')->source, 'String as param to array');
    }
}