<?php

require_once dirname(__FILE__) . '/../../../libs/Qwin.php';
require_once dirname(__FILE__) . '/../../../libs/Qwin/String.php';

/**
 * Test class for Qwin_String.
 * Generated by PHPUnit on 2012-01-18 at 09:09:45.
 */
class Qwin_StringTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Qwin_String
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Qwin_String;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Qwin_String::call
     */
    public function testCall() {
        $widget = $this->object;

        $widget->souce = 10.6;

        $this->assertInternalType('string', $widget->string()->source, 'Int to string');

        $widget->source = true;

        $this->assertInternalType('string', $widget->string()->source, 'Bool to string');

        $widget->source = null;

        $this->assertInternalType('string', $widget->string()->source, 'Null to string');

        $widget->source = array(
            'key' => 'value',
            'key2' => 'value2',
            'key3' => array('value3'),
        );

        $this->assertInternalType('string', $widget->string()->source, 'Array to string');

        $widget->source = Qwin::getInstance()->variable();

        $this->assertInternalType('string', $widget->string()->source, 'Object to string');

        $this->assertInternalType('string', $widget->string(array('list' => 'value'))->source, 'Array as param to string');
    }

}