<?php
require_once dirname(__FILE__) . '/../../../libs/Qwin.php';
require_once dirname(__FILE__) . '/../../../libs/Qwin/Dump.php';

/**
 * Test class for Qwin_Dump.
 * Generated by PHPUnit on 2012-01-18 at 09:09:51.
 */
class Qwin_DumpTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Qwin_Dump
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = Qwin::getInstance()->dump;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Qwin_Dump::__invoke
     */
    public function test__invoke() {
        $widget = $this->object;

        // do not exit after variable dump
        $widget->option('exit', false);

        // test dump invoker, using fake invoker to avoid large infomation output
        $tmp = $widget->invoker;
        $widget->invoker = 'fake invoker';

        ob_start();

        $widget->dump();

        $actual = ob_get_contents();
        ob_end_clean();

        ob_start();

        var_dump($widget->invoker);

        $expected = ob_get_contents();
        ob_end_clean();

        $this->assertEquals($expected, $actual);

        // reset invoker
        $widget->invoker = $tmp;

        // test custome variable
        $var = 'string';

        ob_start();

        $widget->dump($var);

        $actual = ob_get_contents();
        ob_end_clean();

        ob_start();

        var_dump($var);

        $expected = ob_get_contents();
        ob_end_clean();

        $this->assertEquals($expected, $actual);
    }
}
