<?php

require_once dirname(__FILE__) . '/../../../libs/Qwin.php';
require_once dirname(__FILE__) . '/../../../libs/Qwin/IsFile.php';

/**
 * Test class for Qwin_IsFile.
 * Generated by PHPUnit on 2012-01-18 at 09:09:00.
 */
class Qwin_IsFileTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Qwin_IsFile
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Qwin_IsFile;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Qwin_IsFile::call
     * @covers Qwin_IsFile::__construct
     */
    public function testCall() {
        $object = $this->object;

        $this->assertEquals(false, $object->isFile(array()), 'Not File path');

        $this->assertEquals($object->isFile(__FILE__), __FILE__, 'File found');

        $this->assertFalse($object->isFile('.file not found'), 'File not found');

        $paths = explode(PATH_SEPARATOR, ini_get('include_path'));
        $path = array_pop($paths);
        $files = scandir($path);
        foreach ($files as $file) {
            if ('.' == $file || '..' == $file) {
                continue;
            }
            if (is_file($path . DIRECTORY_SEPARATOR . $file)) {
                $this->assertNotEquals(false, $object->isFile($file), 'File in include path found');
                break;
            }
        }

        if (!function_exists('stream_resolve_include_path')) {
            function stream_resolve_include_path() {
                return 'file found.';
            }

            $this->assertNotEquals(false, $object->isFile('file found.'), 'File in include path found');
        }
    }

}

?>
