<?php
require_once dirname(__FILE__) . '/../../../libs/Qwin.php';

/**
 * Test class for Qwin_Url.
 * Generated by PHPUnit on 2012-01-18 at 09:11:18.
 */
class Qwin_UrlTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Qwin_Url
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        Qwin::getInstance();
        $this->object = new Qwin_Url;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Qwin_Url::build
     */
    public function testBuild() {
        $widget = $this->object;

        $url = $widget->build(array(
            'key' => 'value',
            'key2' => array(
                'subkey' => 'value2',
            ),
        ), array(
            'key' => 'value2',
        ));

        $this->assertEquals('?key=value2&key2[subkey]=value2', $url);

        $widget->build();
    }

    /**
     * @covers Qwin_Url::__invoke
     */
    public function test__invoke() {
        $widget = $this->object;

        $url = $widget->url('user', 'login');

        $this->assertEquals('?module=user&action=login', $url);
    }
}
