<?php

require_once dirname(__FILE__) . '/../../../libs/Qwin.php';
require_once dirname(__FILE__) . '/../../../libs/Qwin/Get.php';

/**
 * Test class for Qwin_Get.
 * Generated by PHPUnit on 2012-01-18 at 09:08:17.
 */
class Qwin_GetTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Qwin_Get
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Qwin_Get;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Qwin_Get::call
     */
    public function testCall() {
        $name = $this->object->call('name');
        $source = isset($_GET['name']) ? $_GET['name'] : null;
        
        $this->assertEquals($name->source, $source);
        
        $default = 'default';
        $name2 = $this->object->call('name', $default);
        $source = isset($_GET['name']) ? $_GET['name'] : $default;
        
        $this->assertEquals($name2->source, $default);
        
        $name->source = 'this is a string';
        $name3 = $name->get(1);
        
        $this->assertEquals('h', $name3->source);
        
        $name4 = $name->get(0, 2);
        $this->assertEquals('thi', $name4->source);
        
        $name->source = array(
            'value1',
            'value2',
            'value3',
        );
        $name5 = $name->get(0, 1);
        $this->assertEquals(array('value1', 'value2'), $name5->source);
        
        
        $name6 = $name->get(array());
        $this->assertEquals($name, $name6);
        
        $name7 = $name->get(1, 'not int');
        
        $name8 = $name->get(new stdClass());
    }

}

?>
