<?php

require_once dirname(__FILE__) . '/../../../libs/Qwin.php';
require_once dirname(__FILE__) . '/../../../libs/Qwin/Replace.php';

/**
 * Test class for Qwin_Replace.
 * Generated by PHPUnit on 2012-01-18 at 09:10:31.
 */
class Qwin_ReplaceTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Qwin_Replace
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Qwin_Replace;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Qwin_Replace::call
     */
    public function testCall() {
        $object = $this->object;
        
        $object->source = 'Hello World';
        
        $object->replace('W', 'w');
        
        $this->assertEquals('Hello world', $object->source, 'Replace W to lower');
        
        $object->replace('l', 'x', &$count);
        
        $this->assertEquals(3, $count, 'Replace two chars');
        
        $object->replace('O', 'Q', &$count, false);
        
        $this->assertEquals(2, $count, 'Ignore case');
    }

}

?>
