<?php

require_once dirname(__FILE__) . '/../../../libs/Qwin.php';
require_once dirname(__FILE__) . '/../../../libs/Qwin/IsAjax.php';

/**
 * Test class for Qwin_IsAjax.
 * Generated by PHPUnit on 2012-01-18 at 09:10:08.
 */
class Qwin_IsAjaxTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Qwin_IsAjax
     */
    protected $object;

    /**
     * original value of $_SERVER['HTTP_X_REQUESTED_WITH']
     *
     * @var mixed
     */
    protected $_ajax;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Qwin_IsAjax;

        $this->_ajax = isset($_SERVER['HTTP_X_REQUESTED_WITH']) ?
            $_SERVER['HTTP_X_REQUESTED_WITH'] : new Qwin_Null;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        if (!$this->_ajax instanceof Qwin_Null) {
            $_SERVER['HTTP_X_REQUESTED_WITH'] = $this->_ajax;
        }
    }

    /**
     * @covers Qwin_IsAjax::call
     */
    public function testCall() {
        if (isset($_SERVER['HTTP_X_REQUESTED_WITH'])) {
            unset($_SERVER['HTTP_X_REQUESTED_WITH']);
        }

        $widget = $this->object;

        $this->assertFalse($widget->isAjax());

        $_SERVER['HTTP_X_REQUESTED_WITH'] = 'look like ajax request';

        $this->assertFalse($widget->isAjax());

        $_SERVER['HTTP_X_REQUESTED_WITH'] = 'XmLhTtPrEqUeSt';

        $this->assertTrue($widget->isAjax());
    }

}

?>
