<?php
require_once dirname(__FILE__) . '/../../../libs/Qwin.php';

/**
 * Test class for Qwin_Split.
 * Generated by PHPUnit on 2012-02-13 at 03:13:19.
 */
class Qwin_SplitTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Qwin_Split
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = Qwin::getInstance()->split;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Qwin_Split::call
     */
    public function testCall() {
        $widget = $this->object;

        $widget->source('ABC');

        $widget->split();

        $this->assertEquals(array('A', 'B', 'C'), $widget->source(), 'splited by empty string');

        $widget->source('Apple Pear Orange');

        $widget->split(' ', 2);

        $this->assertEquals(array('Apple', 'Pear Orange'), $widget->source(), 'splited to two chunks');

        $widget->source('Apple Pear Orange');

        $widget->split(' ', -1);

        $this->assertEquals(array('Apple', 'Pear'), $widget->source(), 'ignored last chunk');
    }
}