<?php
require_once dirname(__FILE__) . '/../../../libs/Qwin.php';
require_once dirname(__FILE__) . '/../../../libs/Qwin/Config.php';

/**
 * Test class for Qwin_Config.
 * Generated by PHPUnit on 2012-01-18 at 09:09:57.
 */
class Qwin_ConfigTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Qwin_Config
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Qwin_Config;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Qwin_Config::__invoke
     */
    public function test__invoke() {
        $widget = $this->object;

        $widget->config('key', 'value');

        $this->assertEquals('value', $widget->config('key'));

        $widget->config('first/second', 'value2');

        $this->assertEquals(array('second' => 'value2',), $widget->config('first'));
    }

}
