<?php
require_once dirname(__FILE__) . '/../../../libs/Qwin.php';
require_once dirname(__FILE__) . '/../../../libs/Qwin/ArrayWidget.php';

/**
 * Test class for Qwin_ArrayWidget.
 * Generated by PHPUnit on 2012-01-18 at 09:11:16.
 */
class Qwin_ArrayWidgetTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Qwin_ArrayWidget
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Qwin_ArrayWidget;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Qwin_ArrayWidget::offsetExists
     */
    public function testOffsetExists() {
        $widget = $this->object;

        $widget['key'] = 'value';

        $this->assertTrue(isset($widget['key']));
    }

    /**
     * @covers Qwin_ArrayWidget::offsetGet
     * @covers Qwin_ArrayWidget::offsetSet
     */
    public function testOffsetGet() {
        $widget = $this->object;

        $widget['key'] = 'value1';

        $this->assertEquals('value1', $widget['key']);
    }

    /**
     * @covers Qwin_ArrayWidget::offsetUnset
     */
    public function testOffsetUnset() {
        $widget = $this->object;

        unset($widget['key']);

        $this->assertNull($widget['key']);
    }

    /**
     * @covers Qwin_ArrayWidget::fromArray
     */
    public function testFromArray() {
        $widget = $this->object;

        $widget['key2'] = 'value2';

        $widget->fromArray(array(
            'key1' => 'value1',
            'key2' => 'value changed',
        ));

        $this->assertEquals('value1', $widget['key1']);

        $this->assertEquals('value changed', $widget['key2']);
    }

}

?>
