<?php

require_once dirname(__FILE__) . '/../../../libs/Qwin.php';
require_once dirname(__FILE__) . '/../../../libs/Qwin/IsUrl.php';

/**
 * Test class for Qwin_IsUrl.
 * Generated by PHPUnit on 2012-01-18 at 09:09:20.
 */
class Qwin_IsUrlTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Qwin_IsUrl
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Qwin_IsUrl;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
