<?php
require_once dirname(__FILE__) . '/../../../libs/Qwin.php';
require_once dirname(__FILE__) . '/../../../libs/Qwin/IsQQ.php';

/**
 * Test class for Qwin_IsQQ.
 * Generated by PHPUnit on 2012-01-18 at 09:09:47.
 */
class Qwin_IsQQTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Qwin_IsQQ
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Qwin_IsQQ;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Qwin_IsQQ::__invoke
     */
    public function test__invoke() {
        $widget = $this->object;

        $this->assertFalse($widget->isQQ('1000'), 'Too short');

        $this->assertFalse($widget->isQQ('011111'), 'Should not start with zero');

        $this->assertFalse($widget->isQQ(011111), 'Should not start with zero, even digits');

        $this->assertFalse($widget->isQQ(134.433), 'Not digits');

        $this->assertTrue($widget->isQQ(1234567));
    }
}
