<?php
require_once dirname(__FILE__) . '/../../../libs/Qwin.php';
require_once dirname(__FILE__) . '/../../../libs/Qwin/Trigger.php';

/**
 * Test class for Qwin_Trigger.
 * Generated by PHPUnit on 2012-01-18 at 09:11:08.
 */
class Qwin_TriggerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Qwin_Trigger
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Qwin_Trigger;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * variable for testCall method
     *
     * @var string
     */
    protected $_state;

    /**
     * @covers Qwin_Trigger::__invoke
     */
    public function test__invoke() {
        $widget = $this->object;

        $widget->bind('test', array($this, 'setTextState'));

        $widget->trigger('test', array(
            'state' => 'testing',
        ));

        $this->assertEquals('testing', $this->_state);
    }

    public function setTextState($event, $state)
    {
        $this->_state = $state;
    }
}
