<?php
require_once dirname(__FILE__) . '/../../../libs/Qwin.php';
/**
 * Test class for Qwin_Sort.
 * Generated by PHPUnit on 2012-02-19 at 09:36:56.
 */
class Qwin_SortTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Qwin_Sort
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        Qwin::getInstance();
        $this->object = new Qwin_Sort;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Qwin_Sort::call
     */
    public function testCall() {
        $widget = $this->object;

        $array = array(
            0 => array(
                'id' => 1,
                'order' => 2,
            ),
            1 => array(
                'id' => 2,
                'order' => 1,
            ),
        );

        $this->assertEquals(array(
            0 => array(
                'id' => 2,
                'order' => 1,
            ),
            1 => array(
                'id' => 1,
                'order' => 2,
            ),
        ), $widget->sort($array, 'id', SORT_DESC));

        $this->assertEquals(array(
            0 => array(
                'id' => 2,
                'order' => 1,
            ),
            1 => array(
                'id' => 1,
                'order' => 2,
            ),
        ), $widget->sort($array, 'order', SORT_ASC));

        $this->assertEquals(array(), $widget->sort(array()), 'empty array');
    }

}
