<?php

require_once dirname(__FILE__) . '/../../../libs/Qwin.php';
require_once dirname(__FILE__) . '/../../../libs/Qwin/Apply.php';

/**
 * Test class for Qwin_Apply.
 * Generated by PHPUnit on 2012-01-18 at 09:09:04.
 */
class Qwin_ApplyTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Qwin_Apply
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Qwin_Apply;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Qwin_Apply::call
     */
    public function testCall() {
        $widget = $this->object;

        $widget->source = 'mypassword';

        $this->assertEquals(md5('mypassword'), $widget->apply('md5', array('mypassword')));
    }

}

?>
