<?php

require_once dirname(__FILE__) . '/../../../libs/Qwin.php';
require_once dirname(__FILE__) . '/../../../libs/Qwin/Length.php';

/**
 * Test class for Qwin_Length.
 * Generated by PHPUnit on 2012-01-18 at 09:08:53.
 */
class Qwin_LengthTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Qwin_Length
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Qwin_Length;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Qwin_Length::call
     */
    public function testCall() {
        $widget = $this->object;

        $widget->source = 'string';

        $this->assertEquals($widget->length(), 6);

        $widget->source = array(
            'one apple', 'two pears', 'three bananas',
        );

        $this->assertEquals($widget->length(), 3);

        $widget->source = null;

        $this->assertEquals($widget->length(), 0);

        $widget->source = 10.1;

        $this->assertEquals($widget->length(), 4, 'Convert to sring "10.1"');

        $widget->source = true;

        $this->assertEquals($widget->length(), 1);

        $widget->source = false;

        $this->assertEquals($widget->length(), 0, 'Convert to empty string');
    }

}

?>
