<?php
require_once dirname(__FILE__) . '/../../../libs/Qwin.php';
require_once dirname(__FILE__) . '/../../../libs/Qwin/Reflection.php';

/**
 * Test class for Qwin_Reflection.
 * Generated by PHPUnit on 2012-01-18 at 09:09:07.
 */
class Qwin_ReflectionTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Qwin_Reflection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Qwin_Reflection;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Qwin_Reflection::exportValue
     */
    public function testExportValue() {
        $widget = $this->object;

        $value = 'string';
        $result = Qwin_Reflection::exportValue($value);
        $this->assertEquals('\'string\'', $result);

        $value2 = array('string');
        $result2 = Qwin_Reflection::exportValue($value2);
        $this->assertEquals('array(..)', $result2);

        $value2 = array();
        $result2 = Qwin_Reflection::exportValue($value2);
        $this->assertEquals('array( )', $result2);

        $value3 = true;
        $result3 = Qwin_Reflection::exportValue($value3);
        $this->assertEquals('true', $result3);

        $value4 = null;
        $result4 = Qwin_Reflection::exportValue($value4);
        $this->assertEquals('null', $result4);
    }

    /**
     * @covers Qwin_Reflection::__invoke
     */
    public function test__invoke() {
        $widget = $this->object;

        $this->assertInstanceOf('Qwin_Reflection_Class', $this->object->reflection());
    }

}
