<?php
require_once dirname(__FILE__) . '/../../../libs/Qwin.php';

/**
 * Test class for Qwin_Before.
 * Generated by PHPUnit on 2012-02-16 at 06:11:22.
 */
class Qwin_BeforeTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Qwin_Before
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        Qwin::getInstance();
        $this->object = new Qwin_Before;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Qwin_Before::call
     */
    public function testCall() {
        $widget = $this->object;

        $widget->source('I like pear and apple.');

        $widget->before('pear', 'orange, ');

        $this->assertEquals('I like orange, pear and apple.', $widget->source());

        $widget->before('not found', 'anything');

        $this->assertEquals('I like orange, pear and apple.', $widget->source());

        $widget->before('i', ' ', false);

        $this->assertEquals(' I like orange, pear and apple.', $widget->source());
    }
}