<?php
/**
 * Array
 *
 * Copyright (c) 2009-2010 Twin. All rights reserved.
 *
 * LICENSE:
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @author    Twin Huang <twinh@yahoo.cn>
 * @copyright Twin Huang
 * @license   http://www.opensource.org/licenses/lgpl-license.php LGPL
 * @version   2010-5-11 23:23:48 utf-8 中文
 * @since     2010-5-11 23:23:48 utf-8 中文
 */

class System_Tool_Controller_Array extends Qwin_Trex_Controller
{
    public function actionSort()
    {
$mod_strings = array (
	'LBL_CAPTCHA_HELP_TEXT'=>'Captcha 是一种验证码。 请从 reCAPTCHA (http://recaptcha.net/) 获取一个公有密匙与私有密匙。',
	'CAPTCHA'=>'Captcha 验证',
	'CAPTCHA_PRIVATE_KEY'=>'Captcha 私有密匙',
	'CAPTCHA_PUBLIC_KEY'=>'Captcha 公有密匙',
	'ENABLE_CAPTCHA'=>'开启 reCAPTCHA 验证',
	'ERR_PUBLIC_CAPTCHA_KEY'=> '非法 Captcha 密匙',
	'BTN_REBUILD_CONFIG' => '重建',

	'DESC_DROPDOWN_EDITOR' => '增加、删除或是修改应用程序的下拉列表',
	'DESC_EDIT_CUSTOM_FIELDS' => '编辑为区域配置新增的自定义字段',
	'DESC_FILES_INSTALLED' => '已安装的更新补丁:',
	'DESC_FILES_QUEUED' => '未安装的更新补丁:',
	'DESC_IFRAME' => '增加可以显示任何网站的标签',
	'DESC_MODULES_INSTALLED' => '以下模块已安装:',

	'DOWNLOAD_QUESTION' => '您确定想要下载选中的程序包吗?',
	'ENABLED_OFFLINE_CLIENTS' => '离线客户端可用。',

    'LBL_MINUTES'=>'分',
    'LBL_HOURS'=>'小时',
    'LBL_DAYS'=>'天',
    'LBL_WEEKS'=>'周',
    'LBL_MONTHS'=>'月',

    'LBL_PUBLIC_KEY'=>'共有密匙',
    'LBL_PRIVATE_KEY'=>'私有密匙',

	'ERR_CANNOT_CREATE_RESTORE_FILE' => '错误:不能创建恢复文件',
	'ERR_CREDENTIALS_MISSING' => '缺少您的sugarcrm.com信任书。',
	'ERR_DELETE_RECORD' => '必须指定记录编号才能删除客户。',
	'ERR_ENABLE_CURL' => '请确认您已经启用了curl',
    'ERR_EXPAND_DATABASE_COMPLETED' => '错误：文件restoreExpand.sql的存在表明您已经扩充了数据库中的列.',
    'ERR_INCORRECT_REGEX' => '正则表达式语法不正确。请检查表达式并提供正确的语法',
    'ERR_EMPTY_REGEX_DESCRIPTION' => '请提供对正则表达式的描述。这个描述将在用户创建密码时显示。',
    'ERR_NO_COLUMNS_TO_EXPAND' => '错误：数据库不包含任何字符形定义，字符或文本列扩大.',
	'ERR_NOT_FOR_MSSQL' => '这个设置的功能目前还没完成。',
	'ERR_NOT_FOR_MYSQL' => '这个设置的功能目前还没完成。',
	'ERR_NOT_FOR_ORACLE' => '这个设置的功能目前还没完成。',
	'ERR_NUM_OFFLINE_CLIENTS_MET' => '您已经达到许可证中离线客户端的数量。您必须禁止一个存在的离线客户端，或者更新您的许可证。',
	'ERR_OC_USER_ALREADY_EXISTS' => '您选择的用户已经存在在系统中。',
	'ERR_SUGAR_DEPOT_DOWN' => '系统不可以连接到SugarExchange来查看和下载程序包。',
    'ERR_SMTP_SERVER_NOT_SET'	=> '警告: 电子邮件设置中，SMTP 发信服务器未设置。系统需要该项设置，以发送密码至用户。',
	'ERR_UW_ACCEPT_LICENSE' => '载继续前，您必须接受许可申明',
    'ERR_UW_CONFIG_FAILED'                      => "错误写出config.php文件.",
	'ERR_UW_COPY_FAILED' => '不可以复制文件',
	'ERR_UW_INVALID_VIEW' => '指定无效视图。',
    'ERR_UW_MUST_SELECT_OVERWRITE_OPTION' => '请选择覆盖写选项目',
    'ERR_UW_NO_DEPENDENCY'      => "下列依存项目没有被系统发现.",
    'ERR_UW_NO_FILES'                           => "被复制的文件没有指明.",
    'ERR_UW_NO_INSTALL_FILE'                    => "安装文件没有指明.",
    'ERR_UW_NO_LANG_DESC'                       => "语言魔术没有声明.",
    'ERR_UW_NO_LANG'                            => "语言名称没有声名.",
    'ERR_UW_NO_MANIFEST'                        => "zip文件中找不到manifest.php文件.  不能够继续.",
    'ERR_UW_NO_MODE'                            => "操作模式没有被指定.",
    'ERR_UW_NO_TEMP_DIR'                        => "被复制的文件目录没有指定.",
	'ERR_UW_NO_UPDATE_RECORD' => '不能定位安装记录',
    'ERR_UW_NO_UPLOAD_FILE'                     => "请点击浏览器从您的系统中选择一个文件来上传.<br>\n",
    'ERR_UW_NO_VIEW'                            => "显示没有定义. 请转到管理员主页来导航到这一页.",
    'ERR_UW_NOT_ACCEPTIBLE_TYPE'                => "您在这页上只能上传模块包，主题包和语言包.",
	'ERR_UW_NOT_RECOGNIZED' => '未识别',
	'ERR_UW_NOT_VALID_UPLOAD' => '无效上传。',
    'ERR_UW_ONLY_PATCHES'                       => "您在这页只能上传补丁.",
	'ERR_UW_REMOVE_FAILED' => '不能移除文件',
    'ERR_UW_REMOVE_PACKAGE'                     => "移除文件包时有问题 ",
    'ERR_UW_RUN_SQL'                            => "执行sql文件时发生错误: ",
    'ERR_UW_UPDATE_CONFIG'                      => "使用新版本信息更新文件config.php时发生错误.",
    'ERR_UW_UPLOAD_ERROR'                       => "更新文件时发生错误，请再试!<br>\n",
	'ERROR_FLAVOR_INCOMPATIBLE' => '上传的文件和Sugar Suite的版本(开源版，专业版，企业版)不兼容:',
    'ERROR_LICENSE_EXPIRED'=> "错误：您的许可过期 ",
    'ERROR_LICENSE_EXPIRED2' => " 天数已过.  请到 <a href='index.php?action=LicenseSettings&module=Administration'>'\"许可管理\"</a>  在管理员屏幕输入您的新许可关键字. 如果您在您的许可关键字到期30天内不输入新许可关键字，您将不能在登陆到这个应用中.",
	'ERROR_MANIFEST_TYPE' => '名单文件必须指定程序包类型。',
	'ERROR_PACKAGE_TYPE' => '名单文件指定了一个不能识别的程序包类型。',
    'ERROR_validator_EXPIRED'=> "错误：您验证的关键字过期 ",
    'ERROR_validator_EXPIRED2' => " 天数已过.  请到 <a href='index.php?action=LicenseSettings&module=Administration'>'\"许可管理\"</a> 在管理员界面输入您新的验证关键字.  如果您不在30天关键字验证有效期内输入新验证关键字, 您将不再能登陆这个应用.",
	'ERROR_VERSION_INCOMPATIBLE' => '上传的文件和当前版本的Sugar Suite不兼容:',

    'FATAL_LICENSE_ALTERED' => "您的许可已经改变自上次您验证它的时候. <br> 请转到 <a href='index.php?action=LicenseSettings&module=Administration'>'\"许可管理\"</a>  在管理员界面.",
    'FATAL_LICENSE_EXPIRED'=> "严重: 您许可到期是30多天前",
    'FATAL_LICENSE_EXPIRED2'=> "请到 <a href='index.php?action=LicenseSettings&module=Administration'>'\"许可管理\"</a>  在管理员页更新您的许可信息并存储所有功能项目.",
    'FATAL_LICENSE_REQUIRED' => "严重: 您的许可关键字信息是被需要的.<br>   请到 <a href='index.php?action=LicenseSettings&module=Administration'>'\"许可管理\"</a>  在管理员屏幕来更新您的许可信息并存储全部功能项.",
    'FATAL_validator_EXPIRED'=> "严重: 您有效关键字到期是30多天前",
    'FATAL_validator_EXPIRED2'=> "请到 <a href='index.php?action=LicenseSettings&module=Administration'>'\"许可管理\"</a>  在管理员屏幕来更新您的许可信息和存储的全部功能项.",
    'FATAL_validator_REQUIRED' => "严重: 您验证关键字信息是被需要的 .<br>   请到 <a href='index.php?action=LicenseSettings&module=Administration'>'\"许可管理\"</a>  在管理员屏幕来更新您的许可信息和存储的全部功能项.<br>不是重新保存您的许可信息使其被认证就是导出关键字并导入有效关键字. " ,
	'HDR_LOGIN_PANEL' => '请输入您的sugarcrm.com信任书。',
    'HEARTBEAT_MESSAGE'=>"<BR>Sugar更新结构允许您的服务器来检查查看为您Sugar版本的一个更新是有效的.",

	'LBL_ACCEPT_TERMS' => '接受团队和条件',
	'LBL_ACCEPT' => '接受',
	'LBL_ADMIN_SUGAR_SERVER' => '管理员用户名:',
	'LBL_ADMINISTRATION_HOME_TITLE' => '系统',
    'LBL_ADMINISTRATION_HOME_DESC' =>'配置系统-宽度设置按照您组织机构的特殊性. 用户能废弃一些本地默认设置在他们的我的帐户页面.',
	'LBL_ALLOW_USER_TABS' => '允许用户配置标签',
	'LBL_ALREADY_RUNNING' => '这个服务器以离线客户端运行。',
	'LBL_APPLY_DST_FIX_DESC' => '必要的步骤可以更新时间处理功能(只有MySQL)。',
	'LBL_APPLY_DST_FIX' => '应用夏令时',
	'LBL_AVAILABLE_MODULES' => '可以下载的模块',
	'LBL_AVAILABLE_UPDATES' => '有效更新',
	'LBL_BACKUP_BACK_HOME' => '返回管理员首页',
	'LBL_BACKUP_CONFIRM' => '确认设置',
	'LBL_BACKUP_CONFIRMED' => '设置已确认。点击“备份”按钮来执行备份。',
	'LBL_BACKUP_DIRECTORY_ERROR' => '必须指定备份目录。',
	'LBL_BACKUP_DIRECTORY_EXISTS' => '备份目录不存在，并且不可以新建。',
	'LBL_BACKUP_DIRECTORY_NOT_WRITABLE' => '备份目录存在，但是不可写。',
	'LBL_BACKUP_DIRECTORY_WRITABLE' => '对于Sugar，必须是可写的',
	'LBL_BACKUP_DIRECTORY' => '目录:',
	'LBL_BACKUP_FILE_AS_SUB' => '目标文件在指定的备份目录中作为子目录存在。',
	'LBL_BACKUP_FILE_EXISTS' => '目标文件在目录中已存在。',
	'LBL_BACKUP_FILE_STORED' => '备份成功存储为',
	'LBL_BACKUP_FILENAME_ERROR' => '必须指定备份文件名。',
	'LBL_BACKUP_FILENAME' => '文件名:',
	'LBL_BACKUP_INSTRUCTIONS_1' => '这个工具只备份系统文件，如果需要备份数据库，请使用phpadmin或mysql的备份工具。',
	'LBL_BACKUP_INSTRUCTIONS_2' => '要备份系统为一个zip文件，请输入以下信息:',
	'LBL_BACKUP_RUN_BACKUP' => '运行备份',
	'LBL_BACKUP_TITLE' => '在线备份',
	'LBL_BACKUP' => '安排备份到Sugar在线数据库。从备份中恢复后，启用一个系统。',
	'LBL_BACKUPS_TITLE' => '备份',
	'LBL_BACKUPS' => '执行备份',
	'LBL_BROWSE' => '浏览',
	'LBL_BUG_TITLE' => '缺陷追踪',
    'LBL_BUG_DESC' => '为您的产品保持一个发行列表. 活跃的发行显示在发布在下拉菜单的缺陷记录，缺陷记录在缺陷跟踪模块创建.',
    'LBL_CANCEL_BUTTON_TITLE' => '取消',
	'LBL_CAT_VIEW' => '分类',
	'LBL_CHANGE_NAME_TABS' => '修改标签名称',
	'LBL_CHECK_FOR_UPDATES' => '检查更新',
	'LBL_CHECK_NOW_LABEL' => '立即检查',
	'LBL_CHECK_NOW_TITLE' => '立即检查',
    'LBL_CHECK_DB_VARDEFS' => '对照变量定义检查数据库结构...',
	'LBL_CHOOSE_WHICH' => '选择全域标签',
	'LBL_CHOOSE_WHICH_SUBS'=>'设置系统级别所显示的子面板',
	'LBL_CLEAR_CHART_DATA_CACHE_DESC' => '移除使用过的数据文件。',
	'LBL_CLEAR_CHART_DATA_CACHE_TITLE' => '清除说明数据Cache',
    'LBL_CLEAR_CHART_DATA_CACHE_FINDING'=>'查找文件中...',
    'LBL_CLEAR_CHART_DATA_CACHE_DELETING1'=>'删除图表数据cache文件中...',
    'LBL_CLEAR_CHART_DATA_CACHE_DELETING2'=>'删除:',
    'LBL_CLEAR_THEME_CACHE_DESC'=>'清除主题使用的缓存文件',
    'LBL_CLEAR_THEME_CACHE_TITLE'=>'清除主题缓存',
    'LBL_CLEAR_UNIFIED_SEARCH_CACHE_DELETING1'=>'删除全局查找缓存文件...',
    'LBL_CLEAR_UNIFIED_SEARCH_CACHE_DELETING2'=>'删除:',
    'LBL_CLEAR_PDFFONTS_DESC'=>'清除 PDF 字体缓存文件，在需要时文件会自动创建',
    'LBL_CLEAR_PDFFONTS_DESC_SUCCESS'=>'成功: PDF 字体缓存文件已清除',
    'LBL_CLEAR_PDFFONTS_DESC_FAILURE'=>'错误: 清除 PDF 字体缓存文件失败',
    'LBL_CLEAR_PDF_FONT_CACHE_TITLE'=>'清除 PDF 字体缓存文件',
    'LBL_CLEAR_PDF_FONT_CACHE_DESC'=>'清除用于存储 PDF 字体数据的缓存文件',
	'LBL_CONFIG_CHECK' => '配置文件检查',
	'LBL_CONFIG_TABS' => '拖拽下面的标签来设置是它们是显示还是隐藏。如果您想阻止非管理员用户配置标签，取消选中“允许用户配置标签”。',
	'LBL_CONFIG_SUBPANELS'=>'拖拽下面的模块名以设定它们的子面板是否显示。',
	'LBL_CONFIGURATOR_DESC' => '设置config.php文件',
	'LBL_CONFIGURATOR_TITLE' => '配置',
	'LBL_CONFIGURE_GROUP_TABS_DESC' => '新增和编辑组标签',
	'LBL_CONFIGURE_GROUP_TABS' => '设置组标签',
	'LBL_CONFIGURE_SETTINGS_TITLE' => '系统设置',
	'LBL_CONFIGURE_SETTINGS' => '系统设置',
	'LBL_CONFIGURE_TABS' => '设置标签',
	'LBL_CONFIGURE_UPDATER' => '配置Sugar更新',
	'LBL_CONFIGURE_SUBPANELS' => '设置子面板',
	'LBL_CONTRACT_TITLE' => '合同',
    'LBL_CONTRACT_DESC'=>'为联系人模块定义联系人类型. 当用户创建一个联系人, 下拉菜单的类型显示要选择的联系人类型.',
	'LBL_CONTRACT_TYPES' => '合同类型',
	'LBL_COULD_NOT_CONNECT' => '错误:不能连接到Sugar服务器。请检查在您管理员面板下<a href="index.php?module=Configurator&action=EditView">系统设置</a>的代理设置。上一次尝试连接@',
	'LBL_CREATE_RESOTRE_FILE' => '恢复Expand.sql文件被成功创建。请使用这个文件来恢复列的改变。',
	'LBL_CURRENCY' => '设置货币汇率',
    'LBL_CONNECTOR_SETTINGS' => '连接器设置',
    'LBL_CONNECTOR_SETTINGS_DESC' => '管理连接器设置',
    'LBL_SUGARPDF_SETTINGS' => 'PDF设置',
    'LBL_SUGARPDF_SETTINGS_DESC' => '管理PDF设置',
	'LBL_DENY' => '拒绝',
	'LBL_DIAG_CANCEL_BUTTON' => '取消',
	'LBL_DIAG_EXECUTE_BUTTON' => '执行诊断',
	'LBL_DIAGNOSTIC_ACCESS' => '您必须要有管理员权限才可以运行诊断工具。',
	'LBL_DIAGNOSTIC_BEANLIST_DESC' => '这个信息告诉我们指定的bean文件是否在bean列表中真的存在。当一个不恰当定义的模块加载扩展后，这会是一个问题。',
	'LBL_DIAGNOSTIC_BEANLIST_GREEN' => '绿色表示文件确实存在。',
	'LBL_DIAGNOSTIC_BEANLIST_ORANGE' => '橙色表示没有索引的文件，所以我们不可以查看它。',
	'LBL_DIAGNOSTIC_BEANLIST_RED' => '红色表示文件不存在。',
	'LBL_DIAGNOSTIC_BLBF' => 'BeanList/BeanFiles文件已存在',
	'LBL_DIAGNOSTIC_CALCMD5' => '&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;&nbsp;复制MD5计算的数组',
    'LBL_DIAGNOSTIC_CONFIGPHP'=>'SugarCRM config.php',
	'LBL_DIAGNOSTIC_CUSTOMDIR' => 'SugarCRM自定义目录',
	'LBL_DIAGNOSTIC_DELETED' => '文件已删除',
	'LBL_DIAGNOSTIC_DELETELINK' => '删除诊断文件',
    'LBL_DIAGNOSTIC_FILE' => '文件',
    'LBL_DIAGNOSTIC_ZIP' => '.zip 不存在.<BR><BR>',
    'LBL_DIAGNOSTIC_DELETE_ERROR' => '没有收到一个文件名称或指明一个路径来删除文件<BR><BR>',
    'LBL_DIAGNOSTIC_DELETE_DIE' => '您正试图去删除一个非法诊断文件.',
    'LBL_DIAGNOSTIC_DELETE_RETURN' => '返回到管理员页',
	'LBL_DIAGNOSTIC_DESC' => '为诊断和分析获取系统配置',
	'LBL_DIAGNOSTIC_DONE' => '完成',
	'LBL_DIAGNOSTIC_DOWNLOADLINK' => '下载诊断文件',
	'LBL_DIAGNOSTIC_EXECUTING' => '执行诊断操作...',
	'LBL_DIAGNOSTIC_FILESMD5' => '&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;&nbsp;复制files.md5',
	'LBL_DIAGNOSTIC_GETBEANFILES' => '检查bean文件是否存在...',
	'LBL_DIAGNOSTIC_GETCONFPHP' => '获取config.php文件...',
	'LBL_DIAGNOSTIC_GETCUSTDIR' => '获取自定义路径...',
	'LBL_DIAGNOSTIC_GETMD5INFO' => '获取MD5信息...',
	'LBL_DIAGNOSTIC_GETMYSQLINFO' => 'MySQL信息',
	'LBL_DIAGNOSTIC_GETMYSQLTD' => 'MySQL备份',
	'LBL_DIAGNOSTIC_GETMYSQLTS' => 'MySQL结构',
	'LBL_DIAGNOSTIC_GETPHPINFO' => '获取phpinfo()',
	'LBL_DIAGNOSTIC_GETSUGARLOG' => '获取文件sugarcrm.log',
	'LBL_DIAGNOSTIC_GETTING' => '获取...',
	'LBL_DIAGNOSTIC_MD5' => 'MD5信息',
	'LBL_DIAGNOSTIC_MYSQLDUMPS' => 'MySQL-配置表备份',
	'LBL_DIAGNOSTIC_MYSQLINFO' => 'MySQL-一般信息',
	'LBL_DIAGNOSTIC_MYSQLSCHEMA' => 'MySQL-所有表结构',
	'LBL_DIAGNOSTIC_NO_MYSQL' => '您没有MySQL。MySQL的功能被禁用。',
    'LBL_DIAGNOSTIC_PHPINFO'=>'phpinfo()',
	'LBL_DIAGNOSTIC_SUGARLOG' => 'SugarCRM日志文件',
	'LBL_DIAGNOSTIC_TITLE' => '诊断工具',
	'LBL_DIAGNOSTIC_VARDEFS' => 'Sugar结构输出(VARDEFS)',
	'LBL_DISABLED' => '禁用',
	'LBL_DISPLAY_TABS' => '显示标签',
    'LBL_DO_OVERWRITE_FILES'    => '不重写文件',
	'LBL_DOCUMENTATION_TITLE' => '在线文档',
	'LBL_DOCUMENTATION' => '获取最终用户和管理员的文档',
    'LBL_DONE'  => '完成',
    'LBL_DROP_HERE' => '[拖到这里]',
	'LBL_DROPDOWN_EDITOR' => '编辑下拉框',
	'LBL_DST_APPLY_FIX' => '应用夏令时到已存在的数据.请先备份。',
	'LBL_DST_BEFORE_DESC' => '此修复将改变您的数据。在运行此修复之前，请备份所有数据。',
	'LBL_DST_BEFORE' => '开始之前:',
	'LBL_DST_CURRENT_SERVER_TIME_ZONE_LOCALE' => '服务器时区为:',
	'LBL_DST_CURRENT_SERVER_TIME_ZONE' => '检测时区:',
	'LBL_DST_CURRENT_SERVER_TIME' => '检测本地时间:',
	'LBL_DST_END_DATE_TIME' => '结束日期',
	'LBL_DST_FIX_CONFIRM_DESC' => '请浏览下面信息，确认系统配置是否正确。',
	'LBL_DST_FIX_CONFIRM' => '确认:',
	'LBL_DST_FIX_DONE_DESC' => '夏令时已经成功应用。',
	'LBL_DST_FIX_TARGET' => '目标:',
	'LBL_DST_FIX_USER_TZ' => '这一步将为所有的用户设置时区。',
	'LBL_DST_FIX_USER' => '用户时区:<br>(可选)',
	'LBL_DST_SET_USER_TZ' => '设置用户时区',
	'LBL_DST_START_DATE_TIME' => '开始日期/时间',
	'LBL_DST_UPGRADE' => '更新:',
	'LBL_EDIT_CUSTOM_FIELDS' => '编辑自定义字段',
	'LBL_EDIT_TABS' => '编辑标签',
	'LBL_EMAIL_TITLE' => '电子邮件',
    'LBL_EMAIL_DESC' => '管理外部和内部邮件. 邮件设置必须是被配置，为使用户可以发出邮件和通讯运动.',
    'LBL_EMAIL_ADDRESS_REQUIRED_FOR_FEATURE' => '使用该特性，需要为每个用户设置一个主电子邮件地址.',
	'LBL_ENABLE_MAILMERGE' => '启用邮件合并?',
	'LBL_ENABLED' => '启用',
	'LBL_ERROR_VERSION_INFO' => '错误版权信息，请稍后再试。',
    'LBL_EXCEEDING_OC_LICENSES' =>"错误: 使离线的客户数量当前超出您许可中声明的数量.  请转到 <a href='index.php?module=Administration&action=ListViewOfflineClient'>'\"管理离线客户端\"</a> 在管理员屏幕设置立宪客户无效或更新您的许可.",
    'LBL_EXECUTE'               => '执行',
	'LBL_EXPAND_DATABASE_COLUMNS_DESC' => '扩展某个字符，在数据库中的varchar和text列(只有MSSQL)',
	'LBL_EXPAND_DATABASE_COLUMNS' => '扩展列宽',
	'LBL_EXPAND_DATABASE_TEXT' => '这个工具允许您在SQLServer上为多字节字符的局限性扩展选定数据库作为临时固定列。',
	'LBL_EXPORT_CUSTOM_FIELDS_TITLE' => '导出自定义字段结构',
	'LBL_EXPORT_CUSTOM_FIELDS' => '把自定义字段的定义导出到一个.sugar的文件中',
	'LBL_EXPORT_DOWNLOAD_KEY' => '导出下载密钥',
	'LBL_EXTERNAL_DEV_DESC' => '把自定义字段结构从一个系统移植到另一个系统',
	'LBL_EXTERNAL_DEV_TITLE' => '移植自定义字段',
	'LBL_FORECAST_TITLE' => '销售预测',
    'LBL_FORECAST_DESC'=> '为预测模块定义时间段. 这些时间段显示在预测模块时间段下拉菜单.',
	'LBL_GLOBAL_TEAM_DESC' => '完全可见',
	'LBL_GLOBAL_TEAM_SELECT' => '默认全局团队未找到。请从这个列表中选择一个团队。',
	'LBL_GLOBAL_TEAM' => '重建全局团队的访问权限。',
	'LBL_GO' => '执行',
	'LBL_HELP_BOOKMARK' => '收藏该页',
	'LBL_HELP_EMAIL' => '电子邮件',
	'LBL_HELP_LINK' => '链接到该页',
	'LBL_HELP_PRINT' => '打印',
	'LBL_HIDE_TABS' => '隐藏标签',
	'LBL_HIDDEN_PANELS'=>'隐藏的子面板',
    'LBL_HIDDEN_TABS'=>'隐藏的标签',
    'LBL_HIDE_ADVANCED_OPTIONS'=>'隐藏高级选项',
	'LBL_HT_DONE' => '---完成---',
	'LBL_HT_NO_WRITE_2' => '如果您想保护可以通过浏览器访问的文件，在您的根目录下创建一个.htaccess文件，并加上这些行:',
	'LBL_HT_NO_WRITE' => '不可写入到文件:',
	'LBL_ICF_ADDING' => '增加自定义字段元数据信息 -',
	'LBL_ICF_DROPPING' => '删除–自定义字段元数据信息',
	'LBL_ICF_IMPORT_S' => '导入结构',
	'LBL_IFRAME' => '门户网站',
	'LBL_IMPORT_CUSTOM_FIELDS_DESC' => '<br>导入一个另一个机器导出的.sugar文件。这将使得本及其中的自定义字段结构与另一个机器上的相一致。建议在导入自定义字段结构前将当前的自定义字段结构导出。导入自定义字段结构之后，系统将自动运行自定义字段的更新操作，系统将会显示数据库将要进行哪些改变。如果您认可这些改变，那么请点击底部执行非仿真模式的链接。如果您想要回滚导入操作，只要简单地导入之前导出的结构就可以了。如果执行<br>警告:这将会删除任何之前定义的而又没有出现在.sugar文件中的自定义字段结构，并删除数据库中这些字段对应的数据。',
	'LBL_IMPORT_CUSTOM_FIELDS_STRUCT' => '自定义字段的结构(CustomFieldStruct.sugar)',
	'LBL_IMPORT_CUSTOM_FIELDS_TITLE' => '导入自定义字段结构',
	'LBL_IMPORT_CUSTOM_FIELDS' => '从一个.sugar的文件导入自定义字段的定义',
	'LBL_IMPORT_validator_KEY' => '导入验证密钥',
	'LBL_INBOUND_EMAIL_TITLE' => '收件箱',
	'LBL_LAYOUT' => '增加、移除、修改应用程序的字段、书面位置',
	'LBL_LICENSE_EXPIRE_DATE' => '有效期',
	'LBL_LICENSE_KEY' => '下载密钥',
	'LBL_LICENSE_NUM_LIC_OC' => '离线客户端许可证数',
	'LBL_LICENSE_NUM_PORTAL_USERS' => '门户网站用户数',
	'LBL_LICENSE_USERS' => '用户数',
	'LBL_LICENSE_validator_END' => '验证密钥有效期',
	'LBL_LICENSE_validator_KEY' => '验证密钥',
	'LBL_LICENSE_validator' => '许可证验证',
	'LBL_LICENSE' => '许可证',
	'LBL_LIST_FIRST_CONNECT_DATE' => '第一次连接日期',
	'LBL_LIST_LAST_CONNECT_DATE' => '最后连接日期',
	'LBL_LIST_NUM_SYNCS' => '同步数',
	'LBL_LIST_SET_STATUS' => '设置状态',
	'LBL_LIST_SYSTEM_KEY' => '系统密钥',
	'LBL_LIST_SYSTEM_NAME' => '系统名称',
	'LBL_LIST_VIEW' => '列表',
	'LBL_LOADING' => '加载中，请等待...',

    'LBL_LDAP_TITLE'=>'LDAP 认证支持',
    'LBL_LDAP_ENABLE'=>'开启 LDAP',
    'LBL_LDAP_SERVER_HOSTNAME'=> '服务器:',
    'LBL_LDAP_SERVER_PORT'=> '端口:',
    'LBL_LDAP_ADMIN_USER'=> '用户名:',
    'LBL_LDAP_ADMIN_USER_DESC'=>'用于 Sugar 用户搜索。[可能需要完全的资格]<br>如果为空，将匿名绑定。',
    'LBL_LDAP_ADMIN_PASSWORD'=> '密码:',
	'LBL_LDAP_AUTHENTICATION'=> '认证:',
	'LBL_LDAP_AUTHENTICATION_DESC'=>'使用特定的用户身份绑定 LDAP 服务器',
    'LBL_LDAP_AUTO_CREATE_USERS'=>'自动创建用户:',
    'LBL_LDAP_USER_DN'=>'用户 DN:',
	'LBL_LDAP_GROUP_DN'=>'组 DN:',
	'LBL_LDAP_GROUP_DN_DESC'=>'示例: <em>ou=groups,dc=example,dc=com</em>',
	'LBL_LDAP_USER_FILTER'=>'过滤用户:',
	'LBL_LDAP_GROUP_MEMBERSHIP'=>'组成员:',
	'LBL_LDAP_GROUP_MEMBERSHIP_DESC'=>'用户必须为指定组的成员',
	'LBL_LDAP_GROUP_USER_ATTR'=>'用户属性:',
	'LBL_LDAP_GROUP_USER_ATTR_DESC'=>'使用唯一身份标识检查此人是否为组成员之一。示例: <em>uid</em>',
	'LBL_LDAP_GROUP_ATTR_DESC'=>'使用组的属性来过滤用户的属性。示例: <em>memberUid</em>',
	'LBL_LDAP_GROUP_ATTR'=>'组属性:',
	'LBL_LDAP_USER_FILTER_DESC'=>'验证用户时，可以使用任何任何附加的过滤参数。例如: \nis_sugar_user=1 或 (is_sugar_user=1)(is_sales=1)',
    'LBL_LDAP_LOGIN_ATTRIBUTE'=>'登录属性:',
    'LBL_LDAP_BIND_ATTRIBUTE'=>'绑定属性:',
    'LBL_LDAP_BIND_ATTRIBUTE_DESC'=>'绑定LDAP用户<br>例如:<b>AD:</b>&nbsp;userPrincipalName,&nbsp;<b>openLDAP:</b>&nbsp;userPrincipalName,&nbsp;<b>Mac&nbsp;OS&nbsp;X:</b>&nbsp;uid',
    'LBL_LDAP_LOGIN_ATTRIBUTE_DESC'=>'LDAP用户查找例子:[<b>AD:</b>&nbsp;userPrincipalName] [<b>openLDAP:</b>&nbsp;dn] [<b>Mac&nbsp;OS&nbsp;X:</b>&nbsp;dn]',
    'LBL_LDAP_SERVER_HOSTNAME_DESC'=>'例如:ldap.example.com 或 ldaps://ldap.example.com (SSL)',
    'LBL_LDAP_SERVER_PORT_DESC'=>'例如: 389 或 636 (SSL)',
	'LBL_LDAP_GROUP_NAME'=>'组名:',
	'LBL_LDAP_GROUP_NAME_DESC'=>'例如 cn=sugarcrm',
    'LBL_LDAP_USER_DN_DESC'=>'例如: ou=people,dc=example,dc=com',
    'LBL_LDAP_AUTO_CREATE_USERS_DESC'=> '如果授权用户不存在，Sugar将创建该用户。',
    'LBL_LDAP_ENC_KEY'	=> '加密密钥:',

	'LBL_LOCALE_DB_COLLATION_TITLE' => '数据库校核',
	'LBL_LOCALE_DB_COLLATION' => '校核',
	'LBL_LOCALE_DEFAULT_CURRENCY_ISO4217' => 'ISO4217货币代码',
	'LBL_LOCALE_DEFAULT_CURRENCY_NAME' => '货币',
	'LBL_LOCALE_DEFAULT_CURRENCY_SYMBOL' => '货币符号',
	'LBL_LOCALE_DEFAULT_CURRENCY' => '默认货币',
	'LBL_LOCALE_DEFAULT_DATE_FORMAT' => '默认日期格式',
	'LBL_LOCALE_DEFAULT_DECIMAL_SEP' => '小数点符号',
	'LBL_LOCALE_DEFAULT_LANGUAGE' => '默认语言',
	'LBL_LOCALE_DEFAULT_NAME_FORMAT' => '默认姓名格式',
	'LBL_LOCALE_DEFAULT_NUMBER_GROUPING_SEP' => '千分符',
	'LBL_LOCALE_DEFAULT_SYSTEM_SETTINGS' => '用户界面',
	'LBL_LOCALE_DEFAULT_TIME_FORMAT' => '默认时间格式',
	'LBL_LOCALE_EXAMPLE_NAME_FORMAT' => '实例',
	'LBL_LOCALE_NAME_FORMAT_DESC' => '“s”称谓<br>“f”名<br>“l”姓',
	'LBL_LOCALE_TITLE' => '系统本地设置',
	'LBL_LOCALE' => '设置系统本地配置',
	'LBL_LOGIN_SUGAR_SERVER_DESC' => '-操作此离线客户端的用户名',
	'LBL_LOGIN_SUGAR_SERVER' => '最终用户名:',
	'LBL_MAILBOX_DESC' => '配置监视邮箱帐户',
	'LBL_MANAGE_CONTRACTEMPLATES_TITLE' => '管理合同类型',
	'LBL_MANAGE_CURRENCIES' => '货币',
	'LBL_MANAGE_GROUPS_TITLE' => '管理组',
	'LBL_MANAGE_GROUPS' => '管理组队列',
	'LBL_MANAGE_LAYOUT' => '字段位置',
	'LBL_MANAGE_LICENSE_TITLE' => '许可证管理',
	'LBL_MANAGE_LICENSE' => '管理许可证属性',
	'LBL_MANAGE_LOCALE' => '区域设置',
	'LBL_MANAGE_MAILBOX' => '收件箱',
	'LBL_MANAGE_OFFLINE_CLIENT' => '查看离线客户端',
	'LBL_MANAGE_OPPORTUNITIES' => '商业机会',
    'LBL_MANAGE_PASSWORD_TITLE' => '密码管理',
    'LBL_MANAGE_PASSWORD'=>'管理密码及过期时间',
	'LBL_MANAGE_RELEASES' => '版本',
	'LBL_MANAGE_ROLES_TITLE' => '角色管理',
	'LBL_MANAGE_ROLES' => '管理角色关系和属性',
	'LBL_MANAGE_TEAMS_TITLE' => '团队管理',
	'LBL_MANAGE_TEAMS' => '管理团队成员关系和属性',
	'LBL_MANAGE_TIMEPERIODS_TITLE' => '时段',
	'LBL_MANAGE_TIMEPERIODS' => '管理时段',
	'LBL_MANAGE_USERS_TITLE' => '用户管理',
	'LBL_MANAGE_USERS' => '管理用户账号和密码',
	'LBL_MANAGE_WORKFLOW' => '工作流程管理',
	'LBL_MANUAL_validator_TXT' => '手工验证',
	'LBL_MANUAL_validator' => '如果您一直有自动验证问题，请检查载管理员面板下<a href="index.php?module=Configurator&action=EditView">系统设置</a>中的代理设置。如果您系统环境禁止您的系统通过互联网连接到许可证验证服务器，您应该执行<a href="#"onclick="toggleDisplay(\'mainbody\');toggleDisplay(\'manualbody\');">手动验证</a>步骤。',
	'LBL_MANUAL_validator1' => '步骤1:通过点击下面的按钮来产生一个许可证密钥信息文件。',
	'LBL_MANUAL_validator2' => '然后保存这个文件(usgarkey.lic)到您的本地文件系统中。',
	'LBL_MANUAL_validator3' => '步骤2:把sugarkey.lic文件传送到可以通过浏览器访问互联网的系统。<br><br>到<a href="http://updates.sugarcrm.com/license">http://updates.sugarcrm.com/license</a>并且提交sugarkey.lic文件。<br><br>许可证验证网站会马上执行验证，如果验证成功，它会返回验证密钥文件(sugarvalidatorkey.lic)。',
	'LBL_MANUAL_validator4' => '步骤3:把验证密钥文件(sugarvalidatorkey.lic)传送到SugarCRM系统中。通过下面表单，导入验证密钥:',
	'LBL_MANUAL_validator5' => '在您导入验证密钥后，您就完成了整个手工验证过程。您的系统会更新验证密钥的有效期。',
	'LBL_MANUFACTURERS_TITLE' => '制造商',
	'LBL_MANUFACTURERS' => '设置制造商列表',
	'LBL_MASS_EMAIL_CONFIG_DESC' => '配置电子邮件设置',
	'LBL_MASS_EMAIL_CONFIG_TITLE' => '电子邮件设置',
	'LBL_MASS_EMAIL_MANAGER_DESC' => '管理发件箱中的电子邮件队列',
	'LBL_MASS_EMAIL_MANAGER_HEADER' => '活动邮件管理',
	'LBL_MASS_EMAIL_MANAGER_TITLE' => '管理电子邮件队列',
	'LBL_MASSAGE_MASS_EMAIL_DESC' => 'SugarCRM3.5.1+更新更新大量Email数据。点击',
	'LBL_MASSAGE_MASS_EMAIL' => '为批量发送电子邮件修复GMT日期时间',
	'LBL_MISSING_GLOBAL' => '我们已经注意到有用户缺少全局团队成员关系。如果您要一个全局团队，请检查下面的选项。',
	'LBL_MISSING_PRIVATE' => '我们已经注意到一些用户没有私有团队。如果您要确保所有用户都有私有团队的话，我们建议您修复下面的选项。',
	'LBL_MISSING_TEAMS' => '我们已经注意到您汇报结构和您团队结构的矛盾。如果您要修复这些矛盾，请检查下面的选项。',
    //ModuleInstaller
    'LBL_MI_REBUILDING' => '重建',
    'LBL_MI_SECTION' => '截面...',
    'LBL_MI_UN_CUSTOMFIELD' => '卸载客户化字段...',
    'LBL_MI_IN_CUSTOMFIELD' => '安装客户化字段...',
    'LBL_MI_COMPLETE' => '完成',
    'LBL_MI_UN_BEAN' => '卸载Bean中 :',
    'LBL_MI_IN_BEAN' => '安装Bean中 :',
    'LBL_MI_IN_DASHLETS' => '安装新增栏中 ',
    'LBL_MI_UN_DASHLETS' => '卸载新增栏中 ',
    'LBL_MI_IN_IMAGES' => '安装图象中',
    'LBL_MI_IN_MENUS' => '安装菜单中',
    'LBL_MI_UN_MENUS' => '卸载菜单中',
    'LBL_MI_IN_ADMIN' => '安装管理员段中 ',
    'LBL_MI_UN_ADMIN' => '卸载管理员段中 ',
    'LBL_MI_IN_USER' => '安装用户页段中 ',
    'LBL_MI_UN_USER' => '卸载用户页段中 ',
    'LBL_MI_IN_VAR' => '安装变量定义中',
    'LBL_MI_UN_VAR' => '卸载变量定义中',
    'LBL_MI_IN_SUBPANEL' => '安装子面版布局中',
    'LBL_MI_UN_SUBPANEL' => '卸载子面版布局',
    'LBL_MI_IN_LANG' => '安装语言包中',
    'LBL_MI_UN_LANG' => '卸载语言包中',
    'LBL_MI_IN_RELATIONSHIPS' => '安装关联关系中',
    'LBL_MI_UN_RELATIONSHIPS' => '卸载关联关系中',
    'LBL_MI_UN_RELATIONSHIPS_DROP' => '删除表中 ',
    'LBL_MI_REPAIR_INDICES' => '修复索引中',
	'LBL_MI_IN_CONNECTORS' => '安装连接器',
	'LBL_MI_UN_CONNECTORS' => '卸载连接器',

	'LBL_ML_ACTION' => '行动',
	'LBL_ML_CANCEL' => '取消',
	'LBL_ML_COMMIT' => '提交',
	'LBL_ML_DESCRIPTION' => '说明',
	'LBL_ML_INSTALLED' => '安装日期',
	'LBL_ML_NAME' => '名称',
	'LBL_ML_PUBLISHED' => '公布日期',
	'LBL_ML_TYPE' => '类型',
	'LBL_ML_UNINSTALLABLE' => '可卸载',
	'LBL_ML_VERSION' => '版本',
	'LBL_ML_INSTALL'=>'安装',
	'LBL_ML_ENABLE_OR_DISABLE'=>'启用/不启用',
	'LBL_ML_DELETE'=>'删除',

	'LBL_MODIFY_CREDENTIALS' => '修改信任书',
	'LBL_MODULE_LICENSE' => '请阅读下面许可申明:',
	'LBL_MODULE_LOADER_TITLE' => '模块加载器',
	'LBL_MODULE_LOADER' => '增加/移除模块',
	'LBL_MODULE_NAME' => '系统管理',
	'LBL_MODULE_TITLE' => '系统管理:首页',
	'LBL_MODULES_TO_DOWNLOAD' => '要下载的模块(拖拽到这儿)',
	'LBL_NEVER' => '从不',
	'LBL_NEW_FORM_TITLE' => '新增客户',
	'LBL_NOTIFY_SUBJECT' => '电子邮件主题:',
	'LBL_OC_SEARCH_FORM_TITLE' => '查找离线客户端',
	'LBL_OFFLINE_CLIENT' => '查看连接系统的离线客户端',
	'LBL_OOTB_BOUNCE' => '每晚处理退回的电子邮件',
	'LBL_OOTB_CAMPAIGN' => '每晚批量运行电子邮件市场活动',
	'LBL_OOTB_IE' => '检查收件箱',
	'LBL_OOTB_PRUNE' => '每月1号精简数据库',
	'LBL_OOTB_REPORTS' => '为计划任务产生报表',
	'LBL_OOTB_WORKFLOW' => '使工作流程任务进行',
    'LBL_OOTB_TRACKER'		=> '修剪第一个月的用户历史表',
   	'LBL_UPDATE_TRACKER_SESSIONS' => '更新 tracker_sessions 表',
	'LBL_OOTB_DCE_REPORT'         => '创建收集每天报告的行为',
	'LBL_OOTB_DCE_SALES_REPORT'   => '创建每周销售报告邮件',
	'LBL_OVERWRITE_FILES'   => '重写文件',
	'LBL_PASSWORD_SUGAR_SERVER_DESC' => '-服务器上的一个管理员的用户名和密码',
	'LBL_PASSWORD_SUGAR_SERVER' => '管理员密码:',
	'LBL_PASSWORD' => '密码',
    'LBL_PASSWORD_RESET_MANAGEMENT'=> '重设密码选项',
    'LBL_PASSWORD_RULES_MANAGEMENT'=> '密码规则',
    'LBL_PASSWORD_TEMPLATE' => '电子邮件模板',
    'LBL_PASSWORD_CREATE_TEMPLATE' => '新建',
	'LBL_PASSWORD_EDIT_TEMPLATE' => '编辑',
	'LBL_PASSWORD_GENERATE_TEMPLATE_MSG' => '用于向用户发送系统生成的密码',
    'LBL_PASSWORD_LOST_TEMPLATE_MSG' => '用于向用户发送系统生成的密码重设链接',
    'LBL_PASSWORD_INVALID_LENGTH' => '最小长度必须小于最大长度',
    'LBL_PASSWORD_INVALID_MINLENGTH' => '最小长度必须大于0',
    'LBL_PASSWORD_SYST_GENERATED_PWD_ON' =>'开启系统生成密码的特性',
	'LBL_PASSWORD_SYST_GENERATED_PWD_HELP' => '当该特性启用时，用户可收到系统生成的密码重设链接。该特性需要: 1) 电子邮件设置中，邮件发送服务器配置正确，2) 用户需要有正确的电子邮件地址',
	'LBL_PASSWORD_EXP_AFTER'=> '密码最大使用次数 ',
    'LBL_PASSWORD_FORGOT_FEATURE'=> '开启 忘记密码 特性',
    'LBL_PASSWORD_FORGOT_FEATURE_HELP'=> '启用时，用户可在登陆页面重设密码。 该特性需要: 1) 用户需要有正确的电子邮件地址，2) 电子邮件设置中，邮件发送服务器配置正确。',
    'LBL_PASSWORD_ONE_UPPER_CASE' => '必须包含大写字母 (A-Z)',
    'LBL_PASSWORD_ONE_LOWER_CASE' => '必须包含小写字母 (a-z)',
    'LBL_PASSWORD_ONE_NUMBER' => '必须包含数字 (0-9)',
    'LBL_PASSWORD_ONE_SPECIAL_CHAR' => '至少包含以下字符之一 (~,!,@,#,$,%,^,&,*,(,),_,+,-,=,{,},|)',
    'LBL_PASSWORD_ONLY_LOWCASE' => '只有小写字母',
    'LBL_PASSWORD_LOCKOUT' => '登陆锁定',
    'LBL_PASSWORD_LOCKOUT_ATTEMPT1' => '最大重试次数 ',
    'LBL_PASSWORD_LOCKOUT_ATTEMPT2' => ' 次',
    'LBL_PASSWORD_LOGIN' => '登陆',
    'LBL_PASSWORD_LOGINS' => '次',
    'LBL_PASSWORD_LOGIN_DELAY' => '恢复登陆时间',
    'LBL_PASSWORD_NEEDED_CARACTERS' => '必须包含字符',
    'LBL_PASSWORD_PROHIBITED_CARACTERS' => '不能包含字符',
    'LBL_PASSWORD_MINIMUM_LENGTH'=> '最小长度',
    'LBL_PASSWORD_MAXIMUM_LENGTH'=> '最大长度',
    'LBL_PASSWORD_AND_MAXIMUM_LENGTH'=> '与最大长度',
    'LBL_PASSWORD_FIRSTNAME_PROHIBITED'=> '不允许包含名',
    'LBL_PASSWORD_LASTNAME_PROHIBITED'=> '不允许包含姓',
    'LBL_PASSWORD_SYST_EXPIRATION'=> '密码过期时间',
    'LBL_PASSWORD_SYST_GENERATED_TITLE'=> '系统生成密码',
    'LBL_PASSWORD_USER_EXPIRATION'=> '用户设定密码过期',
    'ERR_PASSWORD_LINK_EXPIRE_TIME'   => '值定一个链接过期时间。',
	'ERR_PASSWORD_EXPIRE_TIME'   => '指定一个密码过期时间',
	'ERR_PASSWORD_EXPIRE_LOGIN'   => '指定一个登陆次数，超过该次数，密码将过期。',
	'ERR_PASSWORD_LOCKOUT_TIME'   => '指定一个最大的在线时间。',
	'ERR_PASSWORD_LOCKOUT_LOGIN'   => '指定一个密码重试次数，超过该次数用户将被锁定。',
	'LBL_PASSWORD_LINK_EXPIRATION'=> '链接过期时间',
	'LBL_PASSWORD_LINK_EXPIRATION_HELP'=> '系统将发送一个链接给用户用来重设密码。',
	'LBL_PASSWORD_REGEX'=> '正则表达式规则',
    'LBL_PASSWORD_REGEX_COMMENT'=> '正则表达式规则描述',
    'LBL_PASSWORD_RULES' => '密码规则',
    'LBL_PASSWORD_LINK_EXP_IN'=> '链接过期时间',
    'LBL_PASSWORD_EXP_IN'=> '密码过期时间',
    'LBL_PASSWORD_USER_RESET' => '用户重设密码',
	'LBL_PERFORM_UPDATE' => '执行更新',
    'LBL_PLUGINS_TITLE' => 'Sugar Forge',
	'LBL_PLUGINS' => '获取插件和其它Sugar Suite扩展。',
	'LBL_PRICE_LIST_TITLE' => '产品和报价',
    'LBL_PRICE_LIST_DESC' => '管理产品分类，沿用生产制造和装运提供者的相关信息.',
	'LBL_PRIVATE_TEAM' => '重建进入私有团队的权限。应用程序的每个用户都有一个私有团队，所有的上线经理都可以访问它。',
	'LBL_PRODUCT_CATEGORIES_TITLE' => '产品类别',
	'LBL_PRODUCT_CATEGORIES' => '更新产品类别列表',
	'LBL_PRODUCT_TYPES_TITLE' => '产品类型',
	'LBL_PRODUCT_TYPES' => '配置产品类型列表',
	'LBL_PRODUCTS_TITLE' => '产品目录',
	'LBL_PRODUCTS' => '在产品类别中输入记录',
	'LBL_PROXY_AUTH' => '授权?',
	'LBL_PROXY_HOST' => '代理主机',
	'LBL_PROXY_ON_DESC' => '使用代理来访问外部信息，比如Sugarupdates。',
	'LBL_PROXY_ON' => '启用代理?',
	'LBL_PROXY_PASSWORD' => '密码',
	'LBL_PROXY_PORT' => '端口',
	'LBL_PROXY_TITLE' => '代理设置',
	'LBL_PROXY_USERNAME' => '用户名',
	'LBL_QUOTES_ORDERS_TITLE' => '报价和定单',
	'LBL_README' => '说明',
	'LBL_REBUILD_AUDIT_DESC' => '重建audit表。',
	'LBL_REBUILD_AUDIT_TITLE' => '重建Audit',
    'LBL_REBUILD_AUDIT_SEARCH' => '查找新audit无效模块',
    'LBL_REBUILD_AUDIT_CREATING' => '创建表 %1$为表 %2$ .<BR>',
    'LBL_REBUILD_AUDIT_SKIP' => 'Audit 表 %1$s 已经存在. 跳过...<BR>',
	'LBL_REBUILD_CONFIG_DESC' => '重建config.php当不是很明确的时候，您可以更新，恢复缺省状态。',
	'LBL_REBUILD_CONFIG' => '重建配置文件',
	'LBL_REBUILD_DASHLETS_DESC_SHORT' => '重建新增栏缓存文件',
	'LBL_REBUILD_DASHLETS_DESC_SUCCESS' => '新增栏缓存文件已重建。',
	'LBL_REBUILD_DASHLETS_DESC' => '移除新增栏缓存，并扫描已知新增栏文件的路径。',
	'LBL_REBUILD_DASHLETS_TITLE' => '重建新增栏',
	'LBL_REBUILD_EXTENSIONS_DESC' => '重建范围包括变量定义，语言包，菜单，和管理员管理',
	'LBL_REBUILD_EXTENSIONS_TITLE' => '重建',
	'LBL_REBUILD_HTACCESS_DESC' => '请直接重建.htaccess文件，限定登陆.',
	'LBL_REBUILD_HTACCESS' => '重建.htaccess文件',
    'LBL_REBUILD_WEBCONFIG_DESC'=>'重建web.config以限制对某些文件的访问',
    'LBL_REBUILD_WEBCONFIG'=>'重建web.config文件',
	'LBL_REBUILD_JAVASCRIPT_LANG_DESC_SHORT' => '重建语言文件的Javascripts版本',
	'LBL_REBUILD_JAVASCRIPT_LANG_DESC' => '移除语言文件的Javascripts版本，它会在需要的时候重建。',
	'LBL_REBUILD_JAVASCRIPT_LANG_TITLE' => '重建Javascripts语言',

    'LBL_REBUILD_JS_FILES_TITLE' => '重建JS压缩的文件',
    'LBL_REBUILD_JS_FILES_DESC_SHORT' => '复制原始全部JS源文件并替换现有JS压缩文件',
    'LBL_REBUILD_CONCAT_JS_FILES_TITLE' => '重建JS组文件',
    'LBL_REBUILD_CONCAT_JS_FILES_DESC_SHORT' => '重新连接并重写存在的组文件为最新版本的组文件',
    'LBL_REBUILD_JS_MINI_FILES_TITLE' => '重建最小化的JS文件',
    'LBL_REBUILD_JS_MINI_FILES_DESC_SHORT' => '拷贝原始全部JS源文件最小化他们, 然后替换现存压缩文件',
    'LBL_REPAIR_JS_FILES_TITLE' => '修复JS文件',
    'LBL_REPAIR_JS_FILES_DESC_SHORT' => '压缩现有JS文件 - 包括任何所做的改变, 但不重写原始JS源文件',
    'LBL_REPAIR_JS_FILES_PROCESSING' => '处理文件中. 这将花费一些时间.  离开这些页面将取消处理, 因此按需要离开或等待确认...',
    'LBL_REPAIR_JS_FILES_DONE_PROCESSING' => '文件处理完成.',
    'LBL_REPAIR_FIELD_CASING_TITLE' => '修复非小写字段',
    'LBL_REPAIR_FIELD_CASING_DESC_SHORT' => '修复包含大写字母的自定义表与元数据文件，系统需要所有字段名小写',
	'LBL_REPAIR_FIELD_CASING_PROCESSING' => '扫描自定义字段与文件...',
    'LBL_REPAIR_FIELD_CASING_SQL_FIELD_META_DATA' => '更新 fields_meta_data 表中 {0} 行',
    'LBL_REPAIR_FIELD_CASING_SQL_CUSTOM_TABLE' => '更新表 {1} 中 {0} 字段',
	'LBL_REBUILD_EXPRESSIONS_TITLE' => '重建表达式引擎插件',
    'LBL_REBUILD_EXPRESSIONS_DESC' => '重建表达式引擎的 javascript 与 PHP 缓存文件。',
	'LBL_REBUILD_REL_DESC' => '重建元数据关系，删除cache文件。',
	'LBL_REBUILD_REL_TITLE' => '重建关系',
    'LBL_REBUILD_REL_PROC_META'=>'处理关联关系元数据用于 ',
    'LBL_REBUILD_REL_PROC_C_META'=>'处理客户关联关系元数据用于 ',
    'LBL_REBUILD_REL_DEL_CACHE'=>'删除关联关系cache文件...<BR>',
    'LBL_REBUILD_REL_UPD_WARNING'=>'更新管理员警告信息...<BR>',
	'LBL_REBUILD_SCHEDULERS_DESC_SHORT' => '重建您内建的工作计划任务。',
	'LBL_REBUILD_SCHEDULERS_DESC_SUCCESS' => '工作计划任务重建完成。',
	'LBL_REBUILD_SCHEDULERS_DESC' => '重建您的工作计划任务将删除所有存在的任务实体和它们各自的日志。所有内建的工作计划任务都会以默认设置重建，包括启用/停用标志。',
	'LBL_REBUILD_SCHEDULERS_TITLE' => '重建工作计划',
	'LBL_REBUILD_WORKFLOW_DESC' => '重建工作流程缓存和编译插件。重新安装后，删除数据表，或者安装新的工作流程插件',
	'LBL_REBUILD_WORKFLOW' => '重建工作流程',
    'LBL_REBUILD_WORKFLOW_CACHE' => '重建工作流Cache...<BR>',
    'LBL_REBUILD_WORKFLOW_COMPILING' => '编译插件中... <BR>',
	'LBL_REBUILD' => '重建',
    'LBL_REGEX_HELP_TITLE'		=>'正则表达式描述',
    'LBL_REGEX_HELP_TEXT'		=>'<b>正则表达式 </b> 提供了一个简明的，富弹性的检测密码中字符的方法，包括特殊字符与字符的模式。您可以使用正则表达式指定一个自定义的密码规则，若不匹配，则密码合格。',
    'LBL_REGEX_DESC_HELP_TEXT'	=>'当用户创建新密码时，该说明将用来提示用户密码的规则。',
	'LBL_RELEASE' => '管理版本',
	'LBL_RENAME_TABS' => '重命名标签',
	'LBL_REPAIR_ACTION' => '您想采取什么行动呢?',
	'LBL_REPAIR_DATABASE_DESC' => '根据vardefs文件定义的表结构修复数据库',
    'LBL_REPAIR_DATABASE_PROCESSING' => '处理数据库和变量定义比对中...',
    'LBL_REPAIR_DATABASE_DIFFERENCES' => "发现数据库与变量不同",
	'LBL_REPAIR_DATABASE_TEXT' => '此工具可以让您更新数据库，匹配beanvardefsandrelationshipmetadata的改变.<br>您有三个选项:<br>显示SQL将显示在屏幕上执行的sql语句<br>导出SQL将导出一个sql文件<br>执行SQL将执行SQL。',
                    "在变量定义. 您有导出这些脚本并然后运行它们的选项 " .
                    "基于您的数据库使用外部数据库挂历工具，或允许" .
                    "管理员模块运行脚本." .
                    "<br><br><strong>NOTE: 任何您在文本箱中做的脚本的改变将被反射 " .
                    "在导出或自行的代码.<br><br>",
    'LBL_REPAIR_DATABASE_SYNCED' => "数据库表是与变量定义同步的",
    'LBL_REPAIR_DATABASE_EXECUTE' => "执行",
    'LBL_REPAIR_DATABASE_EXPORT' => "导出",
	'LBL_REPAIR_DATABASE' => '修复数据库',
	'LBL_REPAIR_DISPLAYSQL' => '显示SQL',
	'LBL_REPAIR_ENTRY_POINTS_DESC' => '检查修复进入点。如果您看到“不是有效进入点”错误，运行这个脚本。',
	'LBL_REPAIR_ENTRY_POINTS' => '修复进入点。',
	'LBL_REPAIR_EXECUTESQL' => '执行SQL',
	'LBL_REPAIR_EXPORTSQL' => '导出SQL',
	'LBL_REPAIR_IE_DESC' => '修复收件箱帐户，加密帐户密码。',
	'LBL_REPAIR_IE_DESC' => '修复收件箱帐户，加密帐户密码。',
	'LBL_REPAIR_IE_DESC' => '修复收件箱帐户，加密帐户密码。',
	'LBL_REPAIR_IE_FAILURE' => '下面收件箱帐户必须手动修复–请重新输入登录名和密码为每个:',
	'LBL_REPAIR_IE_FAILURE' => '下面收件箱帐户必须手动修复–请重新输入登录名和密码为每个:',
	'LBL_REPAIR_IE_FAILURE' => '下面收件箱帐户必须手动修复–请重新输入登录名和密码为每个:',
	'LBL_REPAIR_IE_SUCCESS' => '所有收件箱帐户修复成功！',
	'LBL_REPAIR_IE_SUCCESS' => '所有收件箱帐户修复成功！',
	'LBL_REPAIR_IE_SUCCESS' => '所有收件箱帐户修复成功！',
	'LBL_REPAIR_IE' => '修复收件箱帐户',
	'LBL_REPAIR_IE' => '修复收件箱帐户',
	'LBL_REPAIR_IE' => '修复收件箱帐户',
	'LBL_REPAIR_INDEX_DESC' => '根据vardef文件中的定义，验证',
	'LBL_REPAIR_INDEX' => '修复索引',
    'LBL_REPAIR_INDEX_DROPPING'=>'<BR>删除限制/索引中.',
    'LBL_REPAIR_INDEX_EXECUTING'=>'<BR> 执行中 ',
    'LBL_REPAIR_INDEX_DROP'=>'<BR>删除这些限制/索引.',
    'LBL_REPAIR_INDEX_ADDING'=>'<BR>添加限制/索引.',
    'LBL_REPAIR_INDEX_ADD'=>'<BR><BR>添加这些限制/索引.',
    'LBL_REPAIR_INDEX_ALTERING'=>'<BR>修改限制/索引中.',
    'LBL_REPAIR_INDEX_ALTER'=>'<BR><BR>修改这些限制/索引.',
    'LBL_REPAIR_INDEX_SYNC'=>'<BR><BR><BR> 索引定义在同步中.',
	'LBL_REPAIR_ORACLE_COMMIT_DONE' => '所有查询语句已提交。',
	'LBL_REPAIR_ORACLE_COMMIT' => '提交',
	'LBL_REPAIR_ORACLE_VARCHAR_DESC_LONG_1' => '以下的查询和您的数据库相违背。您可以手工执行它们，或者点击“提交”按钮让SugarCRM来执行它们。',
	'LBL_REPAIR_ORACLE_VARCHAR_DESC_LONG_2' => '没有发现需要更改的VARCHAR2字符型列。',
	'LBL_REPAIR_ORACLE_VARCHAR_DESC' => '把VARCHAR2列从字节型更改为字符型。对支持UTF-8，MBCS是必要的。',
	'LBL_REPAIR_ORACLE_VARCHAR' => '修复Oracle VARCHAR2列',
	'LBL_REPAIR_ROLES_DESC' => '修复所有存在于新加入的支持访问控制的模块和已加入的支持访问控制的模块中的角色。',
	'LBL_REPAIR_ROLES' => '修复角色',
	'LBL_REPAIR_TEAMS_DESC' => '基于用户汇报层次机构，重建私有团队成员关系。',
	'LBL_REPAIR_TEAMS' => '修复团队'  ,
    'LBL_REPAIR_TEAMS_PROCESS_USER'=>'<BR> 用户处理过程中=',
    'LBL_REPAIR_TEAMS_REPORT'=>' reports to=',
    'LBL_REPAIR_TEAMS_SKIP_USER'=>'<BR> 跳过用户=',
    'LBL_REPAIR_TEAMS_NO_PROC'=>'<BR><BR>无任何处理过程...',
    'LBL_REPAIR_THEME_IMAGES'               =>  '优化主题',
    'LBL_REPAIR_THEME_IMAGES_DESC'          =>  '通过消除克隆图像优化主题.',
    'LBL_REPAIR_XSS'                        => '移除 XSS',
    'LBL_REPAIR_ACTIVITIES_DESC' =>'修复活动 (电话, 会议) 结束日期',
    'LBL_REPAIR_ACTIVITIES_TEXT'=>'这个工具允许您为电话和会议设定结束日期.',
    'LBL_REPAIR_ACTIVITIES' =>'修复活动',
	'LBL_CHECK_REPORTS_DESC' =>'检查是否报表仍然有效在升级后并列出检查中查找到的无效报表',
	'LBL_CHECK_REPORTS_TEXT'=>'这个工具润许您检查是否所有您的报表都有效.',
	'LBL_CHECK_REPORTS' =>'检查报表',

    'LBL_ALL'                               => '全部',
    'LBL_REPAIRXSS_COUNT'                   => '发现对象',
    'LBL_REPAIRXSS_INSTRUCTIONS'            => '选择一个模块来移动潜在的 XSS 字符串.  选择 "全部" 来地址化每个模块.<br>点击执行来开始检测和删除过程.',
    'LBL_REPAIRXSS_REPAIRED'                => '修复的对象',
    'LBL_REPAIRXSS_TITLE'                   => '从数据库中删除XSS漏洞',

	'LBL_RESERVE_OC_SPOT' => '保留一个离线客户端的位置',
    'LBL_RESTORE_BUTTON_LABEL' => '恢复',
	'LBL_RETURN' => '返回',
	'LBL_REVALIDATE' => '重新验证' ,
	'LBL_SEARCH_MODULE_NAME' => '输入全部或者部分模块名称:',
	'LBL_SELECT_USER' => '选择用户:',
	'LBL_SEND_STAT' => '<B>发送匿名使用统计表</B>',
	'LBL_SHIPPERS_TITLE' => '运输供应商',
	'LBL_SHIPPERS' => '设置有效出货方式列表',
    'LBL_SHOW_ADVANCED_OPTIONS' => '显示高级选项',
	'LBL_STATUS' => '状态',
    'LBL_TOOLS_DESC' => '创建和编辑模块和模块布局，管理标准和客户化字段, 配置标签, 并定义工作流程. ',
	'LBL_STUDIO_DESC' => '编辑下拉框，自定义字段，布局和标签',
	'LBL_STUDIO_TITLE' => '工作室',
	'LBL_STUDIO' => '工作室',
	'LBL_SUGAR_NETWORK_TITLE' => 'Sugar网络',
    'LBL_SUGAR_NETWORK_DESC' => '在门户支持网站, 访问 SugarCRM 论坛 and Sugar Wiki, 查找 FAQs (频繁问的问题), 下载最新的 Sugar版本, 购买网络脚本, 文件和查找缺陷报告和新功能的请求.',
	'LBL_SUGAR_SCHEDULER_TITLE' => '计划任务',
	'LBL_SUGAR_SCHEDULER' => '建立已安排的事件',
	'LBL_SUGAR_SERVER_URL_DESC' => '这个客户端连接服务器的网址(http://localhost/sugarserver)。',
	'LBL_SUGAR_SERVER_URL' => '服务器网址:',
	'LBL_SUGAR_UPDATE_TITLE' => 'Sugar更新',
	'LBL_SUGAR_UPDATE' => '检查最新的更新。',
	'LBL_SUGARCRM_HELP' => 'Sugar帮助',
	'LBL_SUPPORT_TITLE' => 'Sugar支持服务门户网站',
	'LBL_SUPPORT' => '为技术支持和其它，访问您订制的门户网站',
	'LBL_SYSTEM_NAME' => '系统名称',
	'LBL_TAXRATES_TITLE' => '税率',
	'LBL_TAXRATES' => '配置有效税率列表',
	'LBL_TEAM_HIERARCHY' => '重建团队层次。所有用户不言明的进入团队都会被重建。<Br/>假定用户A汇报给用户B，用户B汇报给用户C。如果用户A可以明确进入团队1，那么用户B和用户C将可以不言明的进入这个团队。',
	'LBL_TERMS_AND_CONDITIONS' => '团队和条件',
    'LBL_THEME_SETTINGS' => '主题设置',
    'LBL_THEME_SETTINGS_DESC' => '选择用户可以使用的主题',
    'LBL_THEME_SETTINGS_AVAILABLE_THEMES' => '可用主题',
    'LBL_THEME_SETTINGS_UNAVAILABLE_THEMES' => '不可用主题',
	'LBL_TIMEZONE' => '时区',
	'LBL_TO' => '到',
	'LBL_UPDATE_CHECK_AUTO' => '自动',
	'LBL_UPDATE_CHECK_MANUAL' => '手动',
	'LBL_UPDATE_CHECK_TYPE' => '<B>自动检查更新</B>',
	'LBL_UPDATE_DESCRIPTIONS' => '说明',
	'LBL_UPDATE_TITLE' => 'Sugar更新',
	'LBL_UPGRADE_ADDED_TO_GROUP' => '增加到组',
	'LBL_UPGRADE_ALREADY_EXISTS_GROUP' => '一个组已经存在',
	'LBL_UPGRADE_ALREADY_EXISTS_IN_GROUP' => '已经存在在组:',
	'LBL_UPGRADE_convert_DISC_CLIENT_TITLE' => '转换离线客户端',
	'LBL_UPGRADE_convert_DISC_CLIENT' => '转换这个Sugar Suite安装包为离线客户端',
	'LBL_UPGRADE_convert_DISC_DESCRIPTION' => '<b>警告:请确认这是没与数据的绿色安装。</b><br>输入下面信息，按保存键装成离线状态。',
	'LBL_UPGRADE_CURRENCY' => '更新货币金额于',
	'LBL_UPGRADE_CUSTOM_LABELS_DESC' => '在每个语言文件中更新用户区标签格式。',
	'LBL_UPGRADE_CUSTOM_LABELS_TITLE' => '更新用户标签',
	'LBL_UPGRADE_DB_BEGIN' => '开始更新',
	'LBL_UPGRADE_DB_COMPLETE' => '更新成功',
	'LBL_UPGRADE_DB_FAIL' => '更新失败',
	'LBL_UPGRADE_DB_TITLE' => '更新数据库',
	'LBL_UPGRADE_DB' => '将2.0.x的数据库升級为2.5',
	'LBL_UPGRADE_FOR_PRODUCT' => '为产品',
	'LBL_UPGRADE_NEW_GROUP' => '已新增的组',
	'LBL_UPGRADE_NOT_UPGRADING' => '未尝试更新',
	'LBL_UPGRADE_STUDIO_DESC' => '为4.5工作室更新4.5版本前的文件',
	'LBL_UPGRADE_STUDIO_TITLE' => '更新工作室',
	'LBL_UPGRADE_SYNC_DISC_CLIENT_TITLE' => '同步客户端',
	'LBL_UPGRADE_SYNC_DISC_CLIENT' => '同步客户端文件和数据到服务器',
	'LBL_UPGRADE_TEAM_CREATE' => '新增团队为-',
	'LBL_UPGRADE_TEAM_EXISTS' => '团队已存在',
	'LBL_UPGRADE_TEAM_TITLE' => '更新团队',
	'LBL_UPGRADE_TEAMS' => '为用户新增团队',
	'LBL_UPGRADE_TITLE' => '修复',
	'LBL_UPGRADE_VERSION' => '更新版本信息',
	'LBL_UPGRADE_WIZARD_TITLE' => '更新向导',
	'LBL_UPGRADE_WIZARD' => '更新向导',
	'LBL_UPGRADE' => '系统修复工具',
	'LBL_UPLOAD_UPGRADE' => '上传更新:',
	'LBL_UPTODATE' => '您有最新的版本',
	'LBL_USER_NAME' => '用户名:',
	'LBL_USERNAME' => '用户名',
	'LBL_USERS_TITLE' => '用户',
    'LBL_USERS_DESC' => '在Sugar中创建，编辑，激活和取消激活用户. 创建和管理团队和角色, 包括模块-字段-访问水平.',




	'LBL_UW_BTN_BACK_TO_MOD_LOADER' => '返回模块加载器',
	'LBL_UW_BTN_BACK_TO_UW' => '返回更新向导',
	'LBL_UW_BTN_DELETE_PACKAGE' => '删除程序包',
	'LBL_UW_BTN_DOWNLOAD' => '下载',
	'LBL_UW_BTN_INSTALL' => '安装',
	'LBL_UW_BTN_UPLOAD' => '上传',
	'LBL_UW_CHECK_ALL' => '全选',
	'LBL_UW_DESC_MODULES_INSTALLED' => '以下模块已安装:',
	'LBL_UW_DESC_MODULES_QUEUED' => '未安装的更新补丁:',
    'LBL_UW_DISABLE'    => '禁用',
    'LBL_UW_ENABLE' => '启用',
	'LBL_UW_FOLLOWING_FILES' => '以下文件是',
	'LBL_UW_HIDE_DETAILS' => '隐藏细节',
	'LBL_UW_INCLUDING' => '包括',
    'LBL_UW_MODULE_READY_DISABLE'   => '模块准备设置为无效.',
    'LBL_UW_MODULE_READY_ENABLE' => '模块准备设置为有效.',
	'LBL_UW_MODULE_READY_UNISTALL' => '模块已经被删除。',
	'LBL_UW_MODULE_READY' => '模块已经被安装。',
	'LBL_UW_NO_FILES_SELECTED' => '未选择的文件会',
    'LBL_UW_NO_INSTALLED_UPGRADES'              => "<i>没有记录升级.</i><br>\n",
	'LBL_UW_NONE' => '无',
    'LBL_UW_NOT_AVAILABLE'                      => "无效",
	'LBL_UW_OP_MODE' => '模块操作:',
    'LBL_UW_PACKAGE_REMOVED'                    => " 已经被移除.<br>\n",
	'LBL_UW_PATCH_READY' => '<h2>准备安装</h2>',
	'LBL_UW_SHOW_DETAILS' => '显示细节',
	'LBL_UW_SUCCESSFUL' => '成功',
	'LBL_UW_UNINSTALL' => '删除',
    'LBL_UW_UPGRADE_SUCCESSFUL'             => "<b>升级应用成功!</b><br>\n",
	'LBL_UW_UPLOAD_MODULE' => '模块',
    'LBL_UW_UPLOAD_SUCCESS'                     => " 已经被上传.<br>",
	'LBL_validator_FAIL_DATE' => '上次失败的验证:',
	'LBL_validator_FILE' => '验证密钥文件',
	'LBL_validator_SUCCESS_DATE' => '上次成功的验证:',
	'LBL_VISIBLE_PANELS'=>'显示的子面板',
    'LBL_VISIBLE_TABS'=>'显示的标签',
	'LBL_WORKFLOW_DESC' => '管理工作流程条件，警告和行动',
	'LBL_WORKFLOW_TITLE' => '工作流程管理',
    'LBL_WORKBENCH' => '工作台',
    'LBL_WORKBENCH_DESC' => '客户化应用并创建新模块.',

	'LNK_DISABLE' => '停用',
	'LNK_ENABLE' => '启用',
	'LNK_FORGOT_PASS' => '忘记了您的密码?',
	'LNK_NEW_ACCOUNT' => '新增账号',
	'LNK_NEW_PRODUCT' => '新增产品',
	'LNK_NEW_TEAM' => '新增团队',
	'LNK_NEW_USER' => '新增用户',
	'LNK_REPAIR_CUSTOM_FIELD' => '修复自定义字段',
	'LNK_SELECT_CUSTOM_FIELD' => '选择自定义字段',
	'LNK_NEW_PORTAL_USER'				=> '创建新的Portal用户',
	'LNK_NEW_GROUP_USER'				=> '创建新的组用户',
    'MI_LBL_DISABLE_DEPEDENCIES' => '这个单元不能被禁用，因为有其他模块都是依赖于这个模块.',
    'MI_REDIRECT_TO_UPGRADE_WIZARD' => '选择这个补丁将您重定向到升级向导，以履行必要的系统检查。你希望继续吗?',
	'ML_DESC_DOCUMENTATION' => '点击一个树结点来查看相关的细节和文档。',
	'ML_LBL_DETAIILS' => '细节',
	'ML_LBL_DO_NOT_REMOVE_TABLES' => '不要移除表',
	'ML_LBL_DOCUMENTATION' => '文件',
	'ML_LBL_INSTALL_FROM_LOCAL' => '从本地文件安装',
	'ML_LBL_INSTALL_FROM_SERVER' => '从sugarExchange安装',
    'ML_LBL_OVERWRITE_FILES'    => '因为您最后一个动作关于这个模块的下列文件已经被改变. 您想采取什么动作呢?',
	'ML_LBL_REMOVE_TABLES' => '移除表',
	'ML_LBL_REVIEWS' => '检查',
	'ML_LBL_SCREENSHOTS' => '截屏',
	'MSG_CONFIG_FILE_READY_FOR_REBUILD' => 'config.php文件可以重建',
	'MSG_CONFIG_FILE_REBUILD_FAILED' => 'config.php文件不能重建。',
	'MSG_CONFIG_FILE_REBUILD_SUCCESS' => 'config.php文件成功重建。',
	'MSG_INCREASE_UPLOAD_MAX_FILESIZE' => '警告:您的PHPconfiguration必须改成允许大与6M的文件上传。请在php.ini中修改文件上传最大值:',
	'MSG_MAKE_CONFIG_FILE_WRITABLE' => '请启动配置文件的写入权限，系统才能够进行更新。',
	'MSG_REBUILD_EXTENSIONS' => '请到<a href="index.php?module=Administration&action=Upgrade">修复</a>界面，点击“重建扩展”。',
	'MSG_REBUILD_RELATIONSHIPS' => '请到<a href="index.php?module=Administration&action=Upgrade">修复</a>界面，点击“重建关系”。',
	'NO_ENABLED_OFFLINE_CLIENTS' => '当前没有可用的离线客户端。',
	'NTC_DISABLE_OFFLINE_CLIENT_ALERT' => '您确定要禁用这个离线客户端吗?',
	'NTC_ENABLE_OFFLINE_CLIENT_ALERT' => '您确定要启用这个离线客户端吗?',
	'NTC_OC_NOT_AVAILABLE' => '无效',
	'NTC_OC_RESERVED' => '保留',
	'REMOVE_QUESTION' => '您确定要移除所选程序包吗?',
    'WARN_POSSIBLE_JS_OVERWRITE'=>'谨慎，这将改写任何您可能已经做的关于javascript文件的改变 ，您愿意继续吗?',
	'WARN_INSTALLER_LOCKED' => '警告:为了保护您的数据，必须设置config.php文件中的变量“installer_locked”为“true”来禁止安装。',
    'WARN_LICENSE_EXPIRED'=> "注意：您的许可过期在 ",
    'WARN_LICENSE_EXPIRED2' =>" 天. 请到 <a href='index.php?action=LicenseSettings&module=Administration'>'\"License Management\"</a>  在Admin屏幕.",
    'WARN_LICENSE_SEATS'=>  "警告: 许可证允许的最大启用用户数已经被超出了1个. ",
    'WARN_LICENSE_SEATS_MAXED'=>  "警告: 启用的用户数已经超出了许可证允许的最大值. ",
    'WARN_LICENSE_SEATS_EDIT_USER'=>  "警告: 启用的用户数已经达到了许可证允许的最大值. ",
    'WARN_LICENSE_SEATS_USER_CREATE'=>"警告: 启用的用户数已经达到了许可证允许的最大值，您将不能创建新的用户。",
    'WARN_LICENSE_SEATS2' => ".  请联系您的销售代表或电子邮件给<a href=\"mailto:cagroup@sugarcrm.com\">cagroup@sugarcrm.com</a>.",
	'WARN_REPAIR_CONFIG' => '注意:config.php文件需要修复。请使用管理员界面下的“修复”链接来修复您的config.php文件。',
    'WARN_UPGRADE_APP'=> "最新版本的应用现已有效. ",
	'WARN_UPGRADE' => '警告:请更新',
	'WARN_UPGRADE2' => '在<a href="index.php?module=Administration&action=Upgrade">管理员面板</a>中使用更新',
    'WARN_validator_EXPIRED'=> "注意: 您验证的关键字过期在 ",
    'WARN_validator_EXPIRED2' =>" 天. 请更新信息在 <a href='index.php?action=LicenseSettings&module=Administration'>'\"License Management\"</a> 页面的 Admin区域.",
	'LBL_MODULEBUILDER'=>'模块生成器',
	'LBL_MODULEBUILDER_DESC'=>'建造新模块来扩充 SugarCRM的功能',
	'LBL_SUGARPORTAL'=>'Sugar 门户',
	'LBL_SUGARPORTAL_DESC' => '管理 Sugar 门户',
	'LBL_CLEAR_TEMPLATE_DATA_CACHE_DESC' => '删除存储的模板文件',
	'LBL_CLEAR_TEMPLATE_DATA_CACHE_TITLE'=>'清除模板的数据缓存',
	'LBL_CLEAR_VARDEFS_DATA_CACHE_TITLE'=>'清除变量定义数据高速缓存',
	'LBL_CLEAR_VARDEFS_DATA_CACHE_DESC'=>'从缓存中清除变量定义',
	'LBL_CLEAR_UNIFIED_SEARCH_CACHE_TITLE'=>'清除全局查找缓存',
	'LBL_CLEAR_UNIFIED_SEARCH_CACHE_DESC'=>'从缓存中删除unified_search_modules.php',
	'LBL_QUICK_REPAIR_AND_REBUILD'=>'快速修复和重建',
    'LBL_QUICK_REPAIR_TITLE'=>'请选择修复的模块:',
	'LBL_FAILED_CONNECTION'=> '连接失败 :',
	'LBL_QUICK_REPAIR_AND_REBUILD_DESC'=>'为选择的模块修复和重建数据库, Extensions, 变量定义, 新增栏等',
	'LBL_ALL_MODULES'=>'所有模块',
	'LBL_CAMPAIGN_CONFIG_TITLE'=>'市场活动邮件设置',
	'LBL_CAMPAIGN_CONFIG_DESC'=>'市场活动邮件设置.',
	'LBL_REPAIR_ORACLE_FULLTEXT'             => '重建全文本索引',
	'LBL_REPAIR_ORACLE_FULLTEXT_DESC'        => '触发一个重建的全文本索引. Oracle 9i 使用者应该频繁运行这个.',
	'LBL_REPAIR'=>'修复',
    'LBL_QR_CBOX_DATAB'=> '修复数据库',
    'LBL_QR_CBOX_CLEARALL'=> '清除所有缓存文件',
    'LBL_QR_CBOX_CLEARTPL'=> '只清除 .tpl文件',
    'LBL_QR_CBOX_CLEARJS'=> '只清除 Javascript文件',
    'LBL_QR_CBOX_CLEARVARDEFS'=> '只清除数据定义',
    'LBL_QR_CBOX_CLEARJSLANG'=> '只清楚Javascript语言文件',
    'LBL_QR_CBOX_CLEARDASHLET'=> '只清除新增栏缓存数据',
    'LBL_QR_CBOX_REBUILDAUDIT'=> '重建审计表',
    'LBL_QR_CBOX_REBUILDEXT'=> '重建Extensions',
    'LBL_QR_CBOX_CLEARLANG'=> '清除语言文件',
    'LBL_QR_CBOX_CLEARSEARCH'=> '清除全局查找缓存',
    'LBL_QR_REBUILDEXT'=>'<h3> 重建Extensions中...</h3>',
    'LBL_QR_CLEARALL'=> '清除所有缓存文件中...完成',
    'LBL_QR_CLEARDASHLET'=>'清除新增栏文件从缓存中...完成',
    'LBL_QR_CLEARTEMPLATE'=>'清除模板文件从缓存中...完成',
    'LBL_QR_CLEARVADEFS'=>'清除数据定义从缓存中...完成',
    'LBL_QR_CLEARJS'=>'清除 JS 文件从缓存中...完成',
    'LBL_QR_CLEARJSLANG'=>'清除 JS 语言文件从缓存中...完成',
    'LBL_QR_CLEARLANG'=>'清除语言文件从缓存中...完成',
    'LBL_QR_CLEARSEARCH'=>'清除全局查找缓存...完成',
    'LBL_QR_REBUILDAUDIT'=>'重建审计表中...',
    'LBL_QR_CBOX_CLEARSUGARFEEDCACHE'=> '清除Sugar Feed缓存',
    'LBL_QR_CLEARSUGARFEEDCACHE'=>'清除Sugar Feed缓存...完成',
    'LBL_QR_CBOX_CLEARTHEMECACHE'=> '清除主题缓存',
    'LBL_QR_CLEARTHEMECACHE'=>'清除主题缓存...完成',
    'LBL_REPAIR_DB_FOR'=>'修复数据库为',
    'LBL_QR_CREATING_TABLE'=>'创建表中',
    'LBL_QR_NOT_AUDIT_ENABLED'=>' 审计无效...<br/>',
	'LBL_QR_CLEARSMARTY'=>'从缓存中清除Smarty模板数据完毕。',//080729
    'LBL_QR_XMLFILES'=>'从缓存中清除XML文件完毕。',
    'LBL_FOR'=>'为',
    'LBL_QR_CBOX_CLEARPDFFONT'=> '清除PDF字体缓存文件',
    'LBL_QR_CLEARPDFFONT'=>'清除PDF字体缓存文件...完成',
















	'EXPORT_DELIMITER' => '导出分隔符',
	'ADMIN_EXPORT_ONLY' => '仅供管理员导出',
	'EXPORT' => '导出设置',
	'EXPORT_CHARSET' => '缺省导出字符集',
	'DISABLE_EXPORT' => '禁用导出',
	'SEARCHING_UPDATES' => '检查更新...',
	'DOWNLOADING' => '下载中...',
	'DL_PACKAGES_DOWNLOADING' => '下载中',
	'DL_PACKAGES_OF' => 'of',
	'DL_PACKAGES_PACKAGES' => '包',
	'LOADING_CATEGORIES' => '正在加载类别...',
	'SEARCHING_PACKAGES' => '查找文件包...',
	'AUTHENTICATING' => '验证中...',
	'LBL_OOTB_DCE_CLNUP' => '在已完成的DCE行为中关闭循环',
	'LBL_IMPORT_INSTANCES_DESC' => '此工具供您将已存在的实例导入DCE。 注意被导入的实例将获得有限的支持和功能.',
	'LBL_IMPORT_INSTANCES' => '导入已存在的实例',
	'LBL_IMPORT_INSTANCE_ACTION' => '已建立导入已有实例的行为.',
	'LBL_TRACKER_SETTINGS' => '跟踪设定',
	'LBL_TRACKER_SETTINGS_DESC' => '启用/停用 跟踪',
    'LBL_SUGARFEED_SETTINGS' => 'Sugar订阅设置',
	'LBL_SUGARFEED_SETTINGS_DESC' => '启用用户订阅和选择模块发布更新 ',
	'LBL_CHECK_YOUR_SCHEMA' => '检查你的表结构',
	'LBL_CHECK_YOUR_SCHEMA_PROCESS' => '为表结构完整性检查',
	'LBL_DATABASE_STATS' => '数据库统计',
	'LBL_DATABASE_STATS_PROCESS' => '此处显示数据库统计',
	'LBL_DCE_TITLE' => 'DCE',
	'LBL_DCE_DESC' => 'Sugar数据中心',
	'LBL_DCE_DCEACTIONS_TITLE' => 'DCE行为',
	'LBL_DCE_DCEACTIONS' => '列出所有能被 集群/客户 服务器执行的动作',
	'LBL_DCE_SETTINGS_TITLE' => 'DCE设定',
	'LBL_DCE_SETTINGS' => '配置DCE',
	'LBL_DN_PROPERTIES_TITLE' => 'DCE客户端属性',
	'LBL_DN_PROPERTIES' => '配置DCE客户端',
	'LBL_UPDATE_CHECK_LOCKOUT_NOTICE' => '如果未选中,系统授权许可到期后管理员必须手动更新许可,否则系统用户将无法登录.',
	'LBL_REPAIR_SEED_USERS_TITLE' => '启用/禁用 种子用户',
	'LBL_REPAIR_SEED_USERS_ACTIVATE' => '启用',
	'LBL_REPAIR_SEED_USERS_DECACTIVATE' => '停用',
	'LBL_REPAIR_SEED_USERS_DESC' => '安装演示时快速启用或者禁用填充种子用户.',
	'LBL_UW_FILES_REMOVED'						=> "下列文件将被从系统中删除:<br>\n",
	'LBL_TEAM_SETS' => '清除未使用的团队组合。',


	'LBL_MODULE_UPLOAD_DISABLE_HELP_TEXT' => '模块加载器被禁止安装新的模块. 可以安装的模块仅限于以下这些预装好的模块.',






	//language changed
	'LBL_DEFAULT_LANGUAGE_CHANGE' => '您的当前语言已被重设为 ',
	'LBL_CURRENT_LANGUAGE_CHANGE' => '系统的默认语言已被重设为 ',
	'ACLRoles'       => 'ACL角色',
	'ACLActions'     => 'ACL行为',
	'ACLFields'      => 'ACL字段',
	'Administration' => '管理员',
	'Audit'  => '审计',
	'CampaignTrackers' => '市场活动跟踪器',
	'Connectors'     => '连接器',
	'ContractTypes'  => '合同类型',
	'Currencies'     => '货币',
	'CustomFields'   => '自定义字段',
	'CustomQueries'  => '自定义查询',
	'DataSets'  => '数据集',
	'DocumentRevisions'  => '文档版本',
	'DynamicFields'  => '动态字段',
	'EmailMan' => '邮差',
	'Employees'      => '员工',
	'Expressions'  => '表达式',
	'Feeds'          => '订阅',
	'EditCustomFields' => '字段元数据',
	'ForecastOpportunities'  => '预测商业机会',
	'ForecastSchedule'  => '预测计划任务',
	'Groups' => '组',
	'Holidays' => '假期',
	'Import_1'       => '导入映射',
	'InboundEmail' => '收件箱',
	'KBContents' => '知识库内容',
	'KBDocumentRevisions' => '知识库文章版本',
	'KBTags' => '知识库标签',
	'KBDocumentKBTags' => '知识库文章标签',
	'Manufacturers'  => '制造商',
	'ProductBundles'   => '产品捆绑',
	'ProductBundleNotes' => '产品捆绑注解',
	'ProjectResources' => '项目资源',
	'Relationships' => '关系',
	'Releases'       => '发布版本',
	'ReportMaker'  => '报表制作器',
	'Roles'  => '角色',
	'Reports_1'      => '已存报表',
	'Schedulers'  => '计划任务',
	'SchedulersJobs'  => '计划任务工作',
	'Shippers'       => '运费',
	'TaxRates'       => '税率',
	'TeamHierarchies'  => '团队架构',
	'TeamMemberships'   => '团队成员',
	'TeamNotices'    => '团队提醒',
	'TeamSets'         => '团队集',
	'TeamSetModules'   => '团队集模块',
	'TimePeriods'    => '时间周期',
	'TrackerPerfs'   => '跟踪器Perf',
	'TrackerQueries' => '跟踪器查询',
	'TrackerSessions'=> '跟踪器会话',
	'UserPreferences'  => '用户偏好',
	'Import_2'       => '导入（最后一次）',
	'Versions'       => '版本',
	'WorkFlowActions'  => '工作流行为',
	'WorkFlowActionShells'  => '工作流行为命令',
	'Worksheet'  => '工作表',
	'WorkFlowTriggerShells'  => '工作流触发器命令',
	'WorkFlowAlertShells'  => '工作流提醒命令',
	'WorkFlowAlerts'  => '工作流提醒',
	'LBL_UW_LANGPACK_READY_DISABLE' =>'停用语言包已就绪。',
	'LBL_UW_LANGPACK_READY_ENABLE' =>'启用语言包已就绪。',
	'LBL_UW_LANGPACK_READY_UNISTALL' =>'卸载语言包已就绪。',
	'LBL_UW_LANGPACK_READY' =>'安装语言包已就绪。',
	'LBL_UW_UNINSTALL_READY' =>'<h2>卸载</h2>',
	'LBL_UW_DISABLE_READY' =>'<h2>停用</h2>',
	'LBL_UW_ENABLE_READY' =>'<h2>启用</h2>',
	'LBL_UW_SUCCESSFULLY' =>'成功地',
	'LBL_UW_TYPE_FULL' =>'完全升级',
	'LBL_UW_TYPE_LANGPACK' =>'语言包',
	'LBL_UW_TYPE_MODULE' =>'模块',
	'LBL_UW_TYPE_PATCH' =>'补丁',
	'LBL_UW_TYPE_THEME' =>'主题',
	'LBL_UW_MODE_INSTALL' =>'已安装',
	'LBL_UW_MODE_UNINSTALL' =>'已卸载',
	'LBL_UW_MODE_DISABLE' =>'已停用',
	'LBL_UW_MODE_ENABLE' =>'已启用',
);

    ksort($mod_strings);
        //print_r($GLOBALS);
        $arr = Qwin::run('Qwin_Helper_Array')->toPhpCode($mod_strings);
        echo '$mod_strings = ' . $arr . ';';
    }
}
