<?php
return array(
    'User' => '用户',
    'Group id' => '分组编号',
    'Username' => '用户名',
    'Email' => '邮箱',
    'Sex' => '性别',
    'Password' => '密码',
    'Birthday' => '生日',
    'Language' => '语言',
    'First name' => '名',
    'Last name' => '姓',
    'Photo' => '照片',
    'Reg ip' => '注册IP',
    'Theme' => '主题',
    'Telephone' => '电话',
    'Mobile' => '手机',
    'Homepage' => '主页',
    'Address' => '地址',
);
