<?php

namespace WidgetTest;

/**
 * Test class for Qwin_Sort.
 * Generated by PHPUnit on 2012-02-19 at 09:36:56.
 */
class SortTest extends TestCase
{
    public function test__invoke()
    {
        $widget = $this->object;

        $array = array(
            0 => array(
                'id' => 1,
                'order' => 2,
            ),
            1 => array(
                'id' => 2,
                'order' => 1,
            ),
        );

        $this->assertEquals(array(
            0 => array(
                'id' => 2,
                'order' => 1,
            ),
            1 => array(
                'id' => 1,
                'order' => 2,
            ),
        ), $widget->sort($array, 'id', SORT_DESC));

        $this->assertEquals(array(
            0 => array(
                'id' => 2,
                'order' => 1,
            ),
            1 => array(
                'id' => 1,
                'order' => 2,
            ),
        ), $widget->sort($array, 'order', SORT_ASC));

        $this->assertEquals(array(), $widget->sort(array()), 'empty array');
    }

}
